### ISSUE TITLE
Lab is not working with import syntax in my project

### ISSUE THREAD

**Issue by AnthonyCouval** [hapijs/lab#1027]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 14.17.6
* *module version*: 24.5.0
* *environment* (e.g. node, browser, native): node API
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi 
* *any other relevant information*: I set "type": "module" in package.json

#### How can we help?

Hello,

I have an issue with Lab, I can't perform tests with my current project.
All my app use "import" syntax with type module activated in package.json. I don't have Babel and I don't use Typescript.
It's a very simple project for now.

Here the error when I try to launch my npm script :

```
Error requiring file: D:\Projects\new-api\test\server.test.js
Must use import to load ES Module: D:\Projects\new-api\test\server.test.js
require() of ES modules is not supported.
require() of test\server.test.js from  D:\Projects\new-api\node_modules\node_modules\@hapi\lab\lib\cli.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\Projects\new-api\routes\server.test.js
require() of ES modules is not supported.
require() of D:\Projects\new-api\routes\server.test.js from D:\Projects\new-api\node_modules\@hapi\lab\lib\cli.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename server.test.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\Projects\new-api\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at D:\Projects\new-api\node_modules\@hapi\lab\lib\cli.js:135:13
    at Array.forEach (<anonymous>)
    at Object.internals.traverse (D:\Projects\new-api\node_modules\@hapi\lab\lib\cli.js:129:15)
    at Object.exports.run (D:\Projects\new-api\node_modules\@hapi\lab\lib\cli.js:60:31)
    at main (D:\Projects\new-api\node_modules\@hapi\lab\bin\lab:56:50)
    at Object.<anonymous> (D:\Projects\new-api\node_modules\@hapi\lab\bin\lab:60:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

Here server.test.js code :

```js
import * as Lab from '@hapi/lab';
import { expect } from '@hapi/code';
import { init } from '../index';

const lab = Lab.script();
const { describe, it, beforeEach,  afterEach} = lab;

describe('GET /', () => {
    let server;

    beforeEach(async () => {
        server = await init();
    });

    afterEach(async () => {
        await server.stop();
    });

    it('responds with 200', async () => {
        const res = await server.inject({
            method: 'get',
            url: '/'
        });
        expect(res.statusCode).to.equal(200);
    });
});

```
And my npm script:
```bash
"test": "lab ./routes/server.test.js"
```
It is confusing because I've tried a lot of things and nothing is working and I don't have this problem with another package.
Am I missing something ?

**Comment by devinivy** [comment]
Unfortunately we don't support ES module projects at the moment, though I expect we'll probably see this working in the future.  It's not ideal, but one option may be to use lab's [transform](https://hapi.dev/module/lab/api?v=24.3.2#transforms) option to "treat" it as a typescript project (which supports that syntax) even though it technically isn't.  For the time being that is the only workaround I can think of 👍

**Comment by devinivy** [comment]
Actually, it may be slightly simpler now since you can use the `--typescript` flag rather than a transform, as of this recent PR: https://github.com/hapijs/lab/pull/1026.

**Comment by AnthonyCouval** [comment]
Oh ok, I probably missed that information about ES module project. Sorry.
Unfortunately even with --typescript flag it's not working. I've tried to put a tsconfig.json in my root app directory and install Typescript.
Is there anything else I should add ?

```bash
> new-api@1.0.0 test D:\Projects\new-api
> lab  --typescript ./test/server.test.js

Error requiring file: D:\Projects\new-api\test\server.test.js
Cannot use import statement outside a module
D:\Projects\new-api\test\server.test.js:1
import * as Lab from '@hapi/lab';
^^^^^^

SyntaxError: Cannot use import statement outside a module
at wrapSafe (internal/modules/cjs/loader.js:988:16)
at Module._compile (internal/modules/cjs/loader.js:1036:27)
at Object.require.extensions.<computed> [as .js] (D:\Projects\new-api\node_modules\@hapi\lab\lib\modules\transform.js:41:28)
at Module.load (internal/modules/cjs/loader.js:937:32)
at Function.Module._load (internal/modules/cjs/loader.js:778:12)
at Module.require (internal/modules/cjs/loader.js:961:19)
at require (internal/modules/cjs/helpers.js:92:18)
at D:\Projects\new-api\node_modules\@hapi\lab\lib\cli.js:135:13
at Array.forEach (<anonymous>)
at Object.internals.traverse (D:\Projects\new-api\node_modules\@hapi\lab\lib\cli.js:129:15)
at Object.exports.run (D:\Projects\new-api\node_modules\@hapi\lab\lib\cli.js:60:31)
at main (D:\Projects\new-api\node_modules\@hapi\lab\bin\lab:56:50)
at Object.<anonymous> (D:\Projects\new-api\node_modules\@hapi\lab\bin\lab:60:1)
at Module._compile (internal/modules/cjs/loader.js:1072:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
at Module.load (internal/modules/cjs/loader.js:937:32)
at Function.Module._load (internal/modules/cjs/loader.js:778:12)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
at internal/main/run_main_module.js:17:47                                                                                     
```

My tsconfig.json :

```typescript
{
    "compilerOptions": {
        "target": "es2021",
        "module": "commonjs",
        "moduleResolution": "node"
    }
}

```

**Comment by kanongil** [comment]
You will need to rename your files to end in `.ts` for that approach to have a chance of working. It will still fail, since you also need to add an `export` before `const lab = …`.

Looking into it, it will be a considerable task to enable ESM-based tests. Mostly because we rely on `require.extensions` to dynamically transform required code to instrument it for the coverage tool. This API has no stable replacement, and can only be enabled through a new experimental API that is quite different in v14 vs v16.

This would probably be simpler to do, if code coverage is updated to use the v8 instrumentation. Then we could use the existing `require` for typescript tests, and `import` for plain `.js` files.

**Comment by devinivy** [comment]
I've been thinking about this recently, and I agree.  There are a couple paths we can take, e.g. integrating with [c8](https://github.com/bcoe/c8) or rolling our own using similar techniques.  I also wrote a module [mo-walk](https://github.com/devinivy/mo-walk) for my own purposes recently that we could fork or expand on, for enumerating and running test files across both cjs and esm.

**Comment by AnthonyCouval** [comment]
Thanks for all these explanations, it's clearer now.
FYI Jest has the same problem, it works with ESM but it's unstable and Mocha works but with some limitations.

**Comment by kanongil** [comment]
Hmm, contrary to the docs, node will actually apply `require.extensions` to ´.js` commonjs files through an `import`. This seems quite suspect, as it will need to determine the type before loading.

This means that it should be somewhat straightforward to support ESM-based test files, as long as all code that needs coverage checks are commonjs `.js` files. I'm not sure it makes much sense with that limitation, though.
