### ISSUE TITLE
External reporters?

### ISSUE THREAD

**Issue by mrlannigan** [hapijs/lab#216]
Is there a reason a reporter cannot be referenced by an alternate javascript file? I have a use case to enable the integration of lab into Webstorm. Without going down the route of added a Java plugin, I was first going to attempt to mimic the output of the Mocha test runner in the Nodejs Plugin that ships with Webstorm. This would require a reporter that outputs something like this:
```
##teamcity[enteredTheMatrix]
##teamcity[testCount count='3']
##teamcity[testSuiteStarted nodeId='1' parentNodeId='0' name='Route' running='false' nodeType='suite' locationHint='suite://Route']
##teamcity[testSuiteStarted nodeId='2' parentNodeId='1' name='.all' running='false' nodeType='suite' locationHint='suite://Route.\.all']
##teamcity[testStarted nodeId='3' parentNodeId='2' name='should add handler' running='false' nodeType='test' locationHint='test://Route.\.all.should add handler']
##teamcity[testStarted nodeId='4' parentNodeId='2' name='should handle VERBS' running='false' nodeType='test' locationHint='test://Route.\.all.should handle VERBS']
##teamcity[testStarted nodeId='5' parentNodeId='2' name='should stack' running='false' nodeType='test' locationHint='test://Route.\.all.should stack']
##teamcity[testStarted nodeId='3' running='true']
##teamcity[testFailed nodeId='3' duration='2' message='AssertionError: expected true not to be truthy' details='    at Assertion.prop.(anonymous function) |[as ok|] (/Users/julian/dev/WebstormProjects/express/node_modules/should/lib/should.js:69:12)|n    at /Users/julian/dev/WebstormProjects/express/test/Route.js:23:34|n    at next (/Users/julian/dev/WebstormProjects/express/lib/router/route.js:90:14)|n    at /Users/julian/dev/WebstormProjects/express/test/Route.js:18:9|n    at Layer.handle |[as handle_request|] (/Users/julian/dev/WebstormProjects/express/lib/router/layer.js:76:5)|n    at next (/Users/julian/dev/WebstormProjects/express/lib/router/route.js:100:13)|n    at Route.dispatch (/Users/julian/dev/WebstormProjects/express/lib/router/route.js:81:3)|n    at Context.<anonymous> (/Users/julian/dev/WebstormProjects/express/test/Route.js:21:13)|n    at Test.Runnable.run (/Users/julian/dev/WebstormProjects/express/node_modules/mocha/lib/runnable.js:216:15)|n    at Runner.runTest (/Users/julian/dev/WebstormProjects/express/node_modules/mocha/lib/runner.js:373:10)|n    at /Users/julian/dev/WebstormProjects/express/node_modules/mocha/lib/runner.js:451:12|n    at next (/Users/julian/dev/WebstormProjects/express/node_modules/mocha/lib/runner.js:298:14)|n    at /Users/julian/dev/WebstormProjects/express/node_modules/mocha/lib/runner.js:308:7|n    at next (/Users/julian/dev/WebstormProjects/express/node_modules/mocha/lib/runner.js:246:23)|n    at Object._onImmediate (/Users/julian/dev/WebstormProjects/express/node_modules/mocha/lib/runner.js:275:5)|n    at processImmediate |[as _immediateCallback|] (timers.js:345:15)' actual='true' expected='undefined']
##teamcity[testStarted nodeId='4' running='true']
##teamcity[testFinished nodeId='4' duration='0']
##teamcity[testStarted nodeId='5' running='true']
##teamcity[testFinished nodeId='5' duration='0']
##teamcity[testSuiteFinished nodeId='2']
##teamcity[testSuiteFinished nodeId='1']
```

So, now this could possibly be a relatively specific use case and so embedding a new reporter may not be the best for this case. But then again, it could be if more people want to integrate this with Webstorm, it just feels a bit hacky. And so this is where the question comes in, can we enable the use of external reporters for a test run?

**Comment by joseph-norman** [comment]
Sounds like something pretty achievable. I think the best case would be to add an `external` property to the list of reporters included in `index.js` internals, like so:-

```
internals.protos = {
    clover: require('./clover'),
    console: require('./console'),
    html: require('./html'),
    json: require('./json'),
    junit: require('./junit'),
    lcov: require('./lcov'),
    tap: require('./tap'),
    external: require('./path/to/external')
};
```

A simple check to see if the external path exists or not could be done afterwards to see if it has been changed or not.

**Comment by joseph-norman** [comment]
Will submit a PR with a potential fix for this

**Comment by joseph-norman** [comment]
Just a thought, an alternative could be passing in a file to the `--reporter` flag when lab is ran at command line (like `lab --reporter yourReporter.js`). And so if the reporter flag value is a file (through some common checks) then to use that. Thoughts?

**Comment by KeKs0r** [comment]
+1 and I would actually prefer to have it configurable form code as well as from CLI.
