### ISSUE TITLE
Lab's tests with node 0.11

### ISSUE THREAD

**Issue by Marsup** [hapijs/lab#296]
While doing a PR, I noticed that lab's own tests won't run at all with node 0.11, many failures, it crashes the test suite before the reporter can tell anything about it.
I don't have time to investigate but I'll take it later if nobody volunteers.

**Comment by AdriVanHoudt** [comment]
I'm getting errors on 0.12 as well

**Comment by Marsup** [comment]
I don't know what has changed but the master is now far better on this.

**Comment by AdriVanHoudt** [comment]
I still get errors locally (v0.12) which don't happen on travis 
```bash
$ npm test

> lab@5.2.1 test c:\Users\...\lab
> make test-cov



  ..............x..............x....................
  .................xxx......xx...xxx.xxx...x..xxx...
  ..x.x..c:\Users\...\lab\node_modules\code\lib\index.js:74
    throw error;
          ^
Error: Expected 1 to equal specified value
    at null.<anonymous> (c:\Users\adri\...\lab\node_modules\code\lib\index.js:167:17)
    at c:\Users\...\lab\test\reporters.js:347:41
    at finalize (c:\Users\...\lab\lib\reporters\index.js:47:112)
    at reporter.finalize (c:\Users\...\lab\lib\reporters\index.js:55:108)
    at c:\Users\...\lab\lib\runner.js:97:104
    at c:\Users...\lab\node_modules\items\lib\index.js:104:25
    at c:\Users\...\lab\lib\runner.js:67:99
    at c:\Users\...\lab\lib\runner.js:147:96
    at c:\Users\...\lab\lib\runner.js:214:89
    at done (c:\Users\...\lab\node_modules\items\lib\index.js:30:25)
    at c:\Users\...\lab\lib\runner.js:209:93
    at done (c:\Users\...\lab\node_modules\items\lib\index.js:30:25)
    at Object.internals.executeDeps (c:\Users\...\lab\lib\runner.js:222:96)
    at steps (c:\Users\...\lab\lib\runner.js:195:107)
    at c:\Users\...\lab\lib\runner.js:201:93
    at iterate (c:\Users\...\lab\node_modules\items\lib\index.js:35:13)
    at done (c:\Users\...\lab\node_modules\items\lib\index.js:27:25)
    at c:\Users...\lab\lib\runner.js:214:89
    at done (c:\Users\...\lab\node_modules\items\lib\index.js:30:25)
    at c:\Users\...\lab\lib\runner.js:209:93
    at done (c:\Users\...\lab\node_modules\items\lib\index.js:30:25)
    at done (c:\Users\...\lab\node_modules\items\lib\index.js:30:25)
    at Immediate._onImmediate (c:\Users\...\lab\lib\runner.js:372:100)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
Makefile:4: recipe for target 'test-cov' failed
make: *** [test-cov] Error 1
npm ERR! Test failed.  See above for more details.
```

**Comment by Marsup** [comment]
Works for me now, I don't know what happened then.

**Comment by AdriVanHoudt** [comment]
#308 reference

**Comment by geek** [comment]
@AdriVanHoudt and @Marsup does this work for you now?  @Marsup added references for node versions and iojs for travis.

**Comment by AdriVanHoudt** [comment]
I saw but he didn't change any code. @arb mentioned in Gitter that there
are some tests that just don't work on windows so that's probably the
issue.

**Comment by geek** [comment]
@AdriVanHoudt if you have an idea for a windows CI to use, we may be able to integrate it into the build process.

**Comment by AdriVanHoudt** [comment]
I can take a look at it

**Comment by Marsup** [comment]
AppVeyor but it's complicated to manage permissions on it. Already using it on lout if you need an example.

**Comment by AdriVanHoudt** [comment]
reference https://github.com/hapijs/lout/blob/master/appveyor.yml

**Comment by geek** [comment]
I tried to get this working on appveyor, didn't have much luck.  I got it down to 35 failing tests :)  

```
Failed tests:
 
  23) CLI doesn't fail with coverage when no external file is being tested:
 
      spawn C:\projects\lab\bin\_lab ENOENT
 
      at exports._errnoException (util.js:746:11)
      at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
      at child_process.js:1144:20
      at process._tickDomainCallback (node.js:381:11)
 
  48) Coverage identifies lines with partial coverage when having external sourcemap:
 
      Expected [Array(2)] to include [Array(2)]
 
      at C:\projects\lab\test\coverage.js:80:37
 
  55) Coverage should not change use strict instructions:
 
      Expected 'function (value) {\n\n    "use strict";...' to include '"use strict"; global.__$$labCov._line(\...'
 
      at C:\projects\lab\test\coverage.js:181:47
 
  88) Leaks ignores Harmony globals:
 
      actual expected
 
      50
 
      Expected 5 to equal specified value
 
      at C:\projects\lab\test\leaks.js:100:33
 
  89) Leaks handles case where Harmony globals do not exist:
 
      actual expected
 
      50
 
      Expected 5 to equal specified value
 
      at C:\projects\lab\test\leaks.js:126:33
 
  90) Leaks identifies custom globals:
 
      actual expected
 
      50
 
      Expected 5 to equal specified value
 
      at C:\projects\lab\test\leaks.js:144:33
 
  101) Reporter outputs to a stream:
 
      actual expected
 
      10
 
      Expected 1 to equal specified value
 
      at C:\projects\lab\test\reporters.js:63:29
 
  102) Reporter outputs to a file:
 
      actual expected
 
      10
 
      Expected 1 to equal specified value
 
      at C:\projects\lab\test\reporters.js:84:29
 
  103) Reporter outputs to a file in a directory:
 
      actual expected
 
      10
 
      Expected 1 to equal specified value
 
      at C:\projects\lab\test\reporters.js:108:29
 
  113) Reporter console generates a report:
 
      actual expected
 
      10
 
      Expected 1 to equal specified value
 
      at C:\projects\lab\test\reporters.js:312:33
 
  114) Reporter console generates a report with errors:
 
      Expected '\n  \n  x\n\nFailed tests:\n\n  1) test...' to match /^\n  \n  x\n\nFailed tests:\n\n  1\) test works:\n\n      actual expected\n\n      truefalse\n\n      Expected true to equal specified value\n\n(?:      at <trace>\n)+\n\n1 of 1 tests failed\nTest duration: \d+ ms\nThe following leaks were detected:x1\n\n$/
 
      at C:\projects\lab\test\reporters.js:339:35
 
  115) Reporter console generates a report with multi-line diff:
 
      Expected '\n  \n  x\n\nFailed tests:\n\n  1) test...' to match /^\n  \n  x\n\nFailed tests:\n\n  1\) test works:\n\n      actual expected\n\n      \[\n        \"a\",\n        \"bc\"\n      \]\n\n      Expected \[ 'a', 'b' \] to equal specified value\n\n(?:      at <trace>\n)+\n\n1 of 1 tests failed\nTest duration: \d+ ms\nThe following leaks were detected:x1\n\n$/
 
      at C:\projects\lab\test\reporters.js:363:35
 
  117) Reporter console generates a report with plain Error:
 
      Expected '\n  \n  x\n\nFailed tests:\n\n  1) test...' to match /^\n  \n  x\n\nFailed tests:\n\n  1\) test fails:\n\n      Error Message\n\n(?:      at <trace>\n)+(?:      at <trace>\n)+(?:      at <trace>\n)+\n\n1 of 1 tests failed\nTest duration: \d+ ms\nNo global variable leaks detected\n\n$/
 
      at C:\projects\lab\test\reporters.js:410:35
 
  118) Reporter console generates a report without progress:
 
      Expected '1 tests complete\nTest duration: 0 ms\n...' to match /^\u001b\[32m1 tests complete\u001b\[0m\nTest duration: \d+ ms\n\u001b\[32mNo global variable leaks detected\u001b\[0m\n\n$/
 
      at C:\projects\lab\test\reporters.js:537:35
 
  119) Reporter console generates a report with verbose progress:
 
      Expected 'test\n  √ 1) works (0 ms)\n\n\n1 tests ...' to match /^test\n  \u001b\[32m✔\u001b\[0m \u001b\[90m1\) works \(\d+ ms\)\u001b\[0m\n\n\n\u001b\[32m1 tests complete\u001b\[0m\nTest duration: \d+ ms\n\u001b\[32mNo global variable leaks detected\u001b\[0m\n\n$/
 
      at C:\projects\lab\test\reporters.js:555:35
 
  123) Reporter console reports correct lines with sourcemaps enabled:
 
      Expected '\n  \n  .\n\n1 tests complete\nTest dur...' to include 'test/coverage/while.js on line(s): 11, ...'
 
      at C:\projects\lab\test\reporters.js:649:35
 
  126) Reporter console generates a report with verbose progress:
 
      Expected 'test\n  √ 1) works (16 ms)\n  ×2) fails...' to match /test\n  ✔ 1\) works \(\d+ ms\)\n  ✖2\) fails\n  \- 3\) skips \(\d+ ms\)\n/
 
      at C:\projects\lab\test\reporters.js:738:35
 
  127) Reporter console excludes colors when terminal does not support:
 
      actual expected
 
      10
 
      Expected 1 to equal specified value
 
      at C:\projects\lab\test\reporters.js:765:33
 
  128) Reporter console displays custom error messages in expect:
 
      Expected '\n  \n  x\n\nFailed tests:\n\n  1) test...' to match /^\n  \n  x\n\nFailed tests:\n\n  1\) test works:\n\n      actual expected\n\n      truefalse\n\n      Not working right: Expected true to equal specified value\n\n(?:      at <trace>\n)+\n\n1 of 1 tests failed\nTest duration: \d+ ms\nNo global variable leaks detected\n\n$/
 
      at C:\projects\lab\test\reporters.js:786:35
 
  134) Reporter console reports with circular JSON:
 
      Expected '\n  \n  x\n\nFailed tests:\n\n  1) test...' to match /^\n  \n  x\n\nFailed tests:\n\n  1\) test works:\n\n      actual expected\n\n      {\n        "a": 12,\n        "b": "\[Circular ~\]"\n      }\n\n      Fail\n\n(?:      at <trace>\n)+\n\n1 of 1 tests failed\nTest duration: \d+ ms\nNo global variable leaks detected\n\n$/
 
      at C:\projects\lab\test\reporters.js:943:35
 
  135) Reporter console reports with undefined values:
 
      Expected '\n  \n  x\n\nFailed tests:\n\n  1) test...' to match /^\n  \n  x\n\nFailed tests:\n\n  1\) test works:\n\n      actual expected\n\n      {\n\s+"a": 1,\n\s+"b": "\[undefined\]",\n\s+"c": "\[function \(\) \{\\n\\n\s+return 'foo';\\n\s+\}\]",\n\s+"d": "\[Infinity\]",\n\s+"e": "\[-Infinity\]"\n\s+}\n\n      Fail\n\n(?:      at <trace>\n)+\n\n1 of 1 tests failed\nTest duration: \d+ ms\nNo global variable leaks detected\n\n$/
 
      at C:\projects\lab\test\reporters.js:975:35
 
  136) Reporter console timeouts generates a report with timeout:
 
      Expected '\n  \n  x\n\nFailed tests:\n\n  1) test...' to match /^\n  \n  x\n\nFailed tests:\n\n  1\) test works:\n\n      Timed out \(\d+ms\) - test works\n\n\n\n1 of 1 tests failed\nTest duration: \d+ ms\nNo global variable leaks detected\n\n$/
 
      at C:\projects\lab\test\reporters.js:430:39
 
  138) Reporter console timeouts doesn't generates a report with timeout on before:
 
      actual expected
 
      10
 
      Expected 1 to equal specified value
 
      at C:\projects\lab\test\reporters.js:496:41
 
  141) Reporter console timeouts doesn't generates a report with timeout on after:
 
      actual expected
 
      10
 
      Expected 1 to equal specified value
 
      at C:\projects\lab\test\reporters.js:496:41
 
  144) Reporter console timeouts doesn't generates a report with timeout on beforeEach:
 
      actual expected
 
      10
 
      Expected 1 to equal specified value
 
      at C:\projects\lab\test\reporters.js:496:41
 
  147) Reporter console timeouts doesn't generates a report with timeout on afterEach:
 
      actual expected
 
      10
 
      Expected 1 to equal specified value
 
      at C:\projects\lab\test\reporters.js:496:41
 
  149) Reporter json generates a report:
 
      actual expected
 
      50
 
      Expected 5 to equal specified value
 
      at C:\projects\lab\test\reporters.js:1019:48
 
  159) Reporter lcov generates a lcov report:
 
      actual expected
 
      10
 
      Expected 1 to equal specified value
 
      at C:\projects\lab\test\reporters.js:1335:33
 
  160) Reporter lcov runs without coverage but doesn't generate output:
 
      actual expected
 
      10
 
      Expected 1 to equal specified value
 
      at C:\projects\lab\test\reporters.js:1364:33
 
  166) Reporter multiple reporters with multiple outputs are supported:
 
      actual expected
 
      10
 
      Expected 1 to equal specified value
 
      at C:\projects\lab\test\reporters.js:1546:38
 
  167) Reporter multiple reporters that are duplicates with multiple outputs are supported:
 
      actual expected
 
      10
 
      Expected 1 to equal specified value
 
      at C:\projects\lab\test\reporters.js:1588:41
 
  184) Runner uses provided linter:
 
      actual expected
 
      10
 
      Expected 1 to equal specified value
 
      at C:\projects\lab\test\runner.js:555:29
 
  185) Runner extends report with assertions library support:
 
      actual expected
 
      10
 
      Expected 1 to equal specified value
 
      at C:\projects\lab\test\runner.js:576:29
 
  187) Runner extends report with assertions library support (incompatible):
 
      actual expected
 
      10
 
      Expected 1 to equal specified value
 
      at C:\projects\lab\test\runner.js:619:29
 
  193) Runner global timeout functions setImmediate still functions correctly:
 
      actual expected
 
      10
 
      Expected 1 to equal specified value
 
      at C:\projects\lab\test\runner.js:957:33
 
 
35 of 205 tests failed
Test duration: 22611 ms
The following leaks were detected:COUNTER_HTTP_CLIENT_REQUEST, COUNTER_HTTP_SERVER_REQUEST, COUNTER_HTTP_CLIENT_RESPONSE, COUNTER_HTTP_SERVER_RESPONSE, COUNTER_NET_SERVER_CONNECTION_CLOSE
Coverage: 99.62% (7/1820)
lib/reporters/console.js missing coverage on line(s): 54, 55, 325, 326, 327, 329, 343
Code coverage below threshold: 99.62 < 100
Linting results: No issues
 
Command exited with code 1
```

Adding here in case we decide to revisit.

Here is the appveyor.yml I landed on

```yml
# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "4.0"

# Install scripts. (runs after repo cloning)
install:
  # Typical npm stuff.
  - npm install
  - cmd: xcopy lib test_runner /Y /I /S

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - cmd: node bin/_lab -fL -t 100 -m 3000 -v

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
```
