### ISSUE TITLE
passing flags to node

### ISSUE THREAD

**Issue by jmonster** [hapijs/lab#305]
I'm looking for a way to pass `--es_staging` to the underlying node process in order to enable ES6 features: https://iojs.org/en/es6.html

Is there an existing way to do this that I've overlooked?

**Comment by Marsup** [comment]
What process ? Lab doesn't spawn child processes except for linting which you probably don't care.

**Comment by jmonster** [comment]
`lab test/file` is certainly using an installed `node` process, no?

**Comment by jmonster** [comment]
I see what you mean though... hmph.

**Comment by Marsup** [comment]
The hashbang is just a shortcut, you can also run `node --es_staging ./node_modules/.bin/lab test/file`.

**Comment by jmonster** [comment]
:+1: brain fart last night; thank you, sir :)

**Comment by pkyeck** [comment]
for me
`node --harmony ./node_modules/.bin/lab`
works, but 
`node --harmony ./node_modules/.bin/lab -t 100`
throws an error, saying: 

```bash
$ node --harmony ./node_modules/.bin/lab -t 100
/Users/xxx/src/index.js:3
abCov._line('/Users/xxx/src/index.js',3);let Hapi = req
                                             ^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/xxx/node_modules/lab/lib/coverage.js:29:36)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/xxx/test/server.post.register.js:6:14)
    at Module._compile (module.js:460:26)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/xxx/node_modules/lab/lib/coverage.js:34:28)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/xxx/node_modules/lab/lib/cli.js:105:23
    at Array.forEach (native)
    at Object.internals.traverse (/Users/xxx/node_modules/lab/lib/cli.js:101:19)
    at Object.exports.run (/Users/xxx/node_modules/lab/lib/cli.js:50:29)
    at Object.<anonymous> (/Users/xxx/node_modules/lab/bin/lab:3:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

seems like the coverage options doesn't like `harmony` stuff ...!?

**Comment by Marsup** [comment]
I get the same error running this code outside of lab, I'd say it's unrelated.

**Comment by pkyeck** [comment]
I don't get it, you ran what code outside of lab?

**Comment by Marsup** [comment]
Just using let. That keyword doesn't seem to be supported by node yet.

**Comment by pkyeck** [comment]
It is - behind the `--harmony` flag at least.

So when I call

```bash
$ run test

> xxx@1.0.0 test /Users/xxx
> node --harmony ./node_modules/.bin/lab

  ........

8 tests complete
Test duration: 46 ms
No global variable leaks detected
```

everything runs as expected - but when I add the `-t 100` part for test coverage, I get the abovementioned error. And I was wondering why.

**Comment by ldesplat** [comment]
On https://github.com/hapijs/lab/blob/master/lib/coverage.js#L208 
Change the options passed and add ecmaFeatures: { blockBindings: true }
Note that I don't know if it will work properly but it will parse :)

I think there is an issue somewhere to make this configurable...

**Comment by pkyeck** [comment]
ok, will try that. thanks :+1:

**Comment by Marsup** [comment]
Sorry but flag or no flag, let doesn't work on either node 0.11 or 0.12, and it gives me exactly your error, so you'd better check that first.

**Comment by ldesplat** [comment]
@Marsup you have to be in strict mode
```javascript
'use strict';
let b = "hi"
console.log(b);
```
Then run `node --harmony test.js`

**Comment by Marsup** [comment]
Then maybe lab also changes that 1st line, making it non-strict, that would explain having the same error.

**Comment by Marsup** [comment]
PR done, just have to wait for @geek now :)
