### ISSUE TITLE
Be more tolerant of espree parser errors

### ISSUE THREAD

**Issue by geek** [hapijs/lab#363]
related https://github.com/hapijs/lab/issues/358

Try with tolerant: true or simply parse template strings.

**Comment by jmonster** [comment]
Interestingly, template strings have been working for me for the past few days, but suddenly today [with a fresh `npm install` -- there's no shrinkwrap in this project yet] it's breaking on *arrow functions*, i.e. `(argument1, argument2) => { /* ... */ }`.

```bash
Line 71: Invalid left-hand side in assignment

      at throwError (/Users/jd/Documents/some-project/node_modules/lab/node_modules/espree/espree.js:2074:17)
      at throwErrorTolerant (/Users/jd/Documentssome-project/node_modules/lab/node_modules/espree/espree.js:2086:20)
      at parseAssignmentExpression (/Users/jd/Documents/some-project/node_modules/lab/node_modules/espree/espree.js:3508:13)
```

Any ideas?

**Comment by geek** [comment]
This is no longer an issue.  espree removed the tolerant option https://www.npmjs.com/package/espree#differences-from-espree-2x

We are also using template strings in our lab code without issues
