### ISSUE TITLE
issue with source-map-support for es6 transpiled code

### ISSUE THREAD

**Issue by RyanPMcD** [hapijs/lab#374]
I have been using lab with lab-babel to test my hapi application written in es6 and transpiled with babel. I am running into this error in my tests:
```
undefined:1
�w���z�&����)඄��)�m��
^
SyntaxError: Unexpected token �
    at Object.parse (native)
    at new SourceMapConsumer (/usr/local/src/node_modules/lab/node_modules/source-map-support/node_modules/source-map/lib/source-map/source-map-consumer.js:50:24)
    at mapSourcePosition (/usr/local/src/node_modules/lab/node_modules/source-map-support/source-map-support.js:120:14)
    at wrapCallSite (/usr/local/src/node_modules/lab/node_modules/source-map-support/source-map-support.js:270:20)
    at /usr/local/src/node_modules/lab/node_modules/source-map-support/source-map-support.js:304:26
    at Array.map (native)
    at Function.prepareStackTrace (/usr/local/src/node_modules/lab/node_modules/source-map-support/source-map-support.js:303:24)
    at process.handleUncaughtExceptions (/usr/local/src/node_modules/lab/node_modules/source-map-support/source-map-support.js:338:23)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:301:26)
```
It appears that this is something that has been addressed in the latest source-map-support module (https://github.com/evanw/node-source-map-support/pull/48) but unfortunately lab 5.10 is only requiring source-map-support 0.2.10. Please look at updating dependencies to help resolve this. Thanks

**Comment by AdriVanHoudt** [comment]
you are always free to do a PR yourself and this seems like an easy one
