### ISSUE TITLE
Missing exports.lab causes error when generating html coverage report 

### ISSUE THREAD

**Issue by rjrodger** [hapijs/lab#399]
I forgot to 'exports.lab = ...' in one test file, and it caused error as below.
Adding the export removed the error.

Probably needs a more informative message?

$ ./node_modules/.bin/lab -P test -r html -o test/coverage.html

/Users/richard/Projects/seneca/node_modules/lab/lib/cli.js:114
                options.output.write('The file: ' + file + ' includes a lab sc
                               ^
TypeError: Object test/coverage.html has no method 'write'
    at /Users/richard/Projects/seneca/node_modules/lab/lib/cli.js:114:32
    at Array.forEach (native)
    at Object.internals.traverse (/Users/richard/Projects/seneca/node_modules/lab/lib/cli.js:99:19)
    at Object.exports.run (/Users/richard/Projects/seneca/node_modules/lab/lib/cli.js:48:29)
    at Object.<anonymous> (/Users/richard/Projects/seneca/node_modules/lab/bin/lab:3:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by geek** [comment]
Good point, we can make this error behave better with custom reporters
