### ISSUE TITLE
Custom reporters not allowed from cli

### ISSUE THREAD

**Issue by geek** [hapijs/lab#415]
Need to allow custom reporters to be allowed by the CLI, as reported by the readme

**Comment by PizzaBrandon** [comment]
Sorry to bother on a closed ticket, but I'm not sure if what I'm dealing with is a related bug or if I'm using this incorrectly.

I just wrote and published a Lab reporter for Bamboo, installed it locally on a package I'm attempting to test, installed `lab` globally (verified it's 5.15.1), and ran `lab -r lab-bamboo-reporter`. It gave me the following error:

```
~/workspaces/project-under-test$ lab -r lab-bamboo-reporter
module.js:338
    throw err;
          ^
Error: Cannot find module 'lab-bamboo-reporter'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.internals.requireReporter (/Users/###/.nvm/versions/node/v0.12.7/lib/node_modules/lab/lib/reporters/index.js:34:12)
    at Object.exports.generate (/Users/###/.nvm/versions/node/v0.12.7/lib/node_modules/lab/lib/reporters/index.js:59:65)
    at Object.exports.report (/Users/###/.nvm/versions/node/v0.12.7/lib/node_modules/lab/lib/runner.js:58:30)
    at Object.exports.run (/Users/###/.nvm/versions/node/v0.12.7/lib/node_modules/lab/lib/cli.js:49:19)
    at Object.<anonymous> (/Users/###/.nvm/versions/node/v0.12.7/lib/node_modules/lab/bin/lab:3:23)
    at Module._compile (module.js:460:26)
    ...
```

But if I run `lab -r ./node_modules/lab-bamboo-reporter`, it succeeds.

Am I reading the usage instructions wrong and `lab` expects the plugin to be installed globally or is this a bug in the implementation?

**Comment by geek** [comment]
Interesting.  What if you install locally and run lab?  I like to avoid global installs and just use the local binaries.  If you don't have the path setup for ./node_modules/.bin then you can run as:

`./node_modules/.bin/lab -r lab-bamboo-reporter`

I wonder if this is an issue with the global install not respecting the current working directory.

**Comment by PizzaBrandon** [comment]
`$ ./node_modules/.bin/lab -r lab-bamboo-reporter` gives the correct test result output.

**Comment by PizzaBrandon** [comment]
I will amend my package's usage instructions to match this requirement, but I do hope you are able to find a solution that allows the global install to also work since the readme recommends it as a best practice.
