### ISSUE TITLE
hiding server 500 errors from console output

### ISSUE THREAD

**Issue by epikhighs** [hapijs/lab#423]
Hi,

This is a usage and/or feature enhancement question.  When using lab, if one of my routes reply() with a hapi/boom 500 response, then a stack trace is outputted to console.  Even after debugging, I can't figure out where in the code this is being outputted. 

I'm wondering if there's a way to disable logging these 500 server responses so that I can more easily determine tests that are passing.

Below is a sample output of what I see in my console.

" at Object.exports.create (c:\project\outbox-service\node_modules\boom\lib\index.js:21:17)" simply points to where the boom error is created.  That is not where the logging occurs.  So I have no idea who's doing this logging.

Thanks.

Debug: internal, implementation, error
    Error: Could not upload.
    at Object.exports.create (c:\project\outbox-service\node_modules\boom\lib\index.js:21:17)
    at Object.exports.internal (c:\project\outbox-service\node_modules\boom\lib\index.js:262:99)
    at Object.exports.badImplementation (c:\project\outbox-service\node_modules\boom\lib\index.js:298:23)
    at Object.module.exports.boom.badImplementation (c:\project\outbox-service\src\server-util.js:25:26)
    at c:\project\outbox-service\src\uploader-route.js:60:39
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at tryCatcher (c:\project\outbox-service\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (c:\project\outbox-service\node_modules\bluebird\js\main\promise.js:503:31)
    at Promise._settlePromiseAt (c:\project\outbox-service\node_modules\bluebird\js\main\promise.js:577:18)
    at Promise._settlePromises (c:\project\outbox-service\node_modules\bluebird\js\main\promise.js:693:14)
    at Async._drainQueue (c:\project\outbox-service\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (c:\project\outbox-service\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\project\outbox-service\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
500

  .....Debug: internal, implementation, error
    Error: Could not upload.
    at Object.exports.create (c:\project\outbox-service\node_modules\boom\lib\index.js:21:17)
    at Object.exports.internal (c:\project\outbox-service\node_modules\boom\lib\index.js:262:99)
    at Object.exports.badImplementation (c:\project\outbox-service\node_modules\boom\lib\index.js:298:23)
    at Object.module.exports.boom.badImplementation (c:\project\outbox-service\src\server-util.js:25:26)
    at c:\project\outbox-service\src\uploader-route.js:60:39
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at tryCatcher (c:\project\outbox-service\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (c:\project\outbox-service\node_modules\bluebird\js\main\promise.js:503:31)
    at Promise._settlePromiseAt (c:\project\outbox-service\node_modules\bluebird\js\main\promise.js:577:18)
    at Promise._settlePromises (c:\project\outbox-service\node_modules\bluebird\js\main\promise.js:693:14)
    at Async._drainQueue (c:\project\outbox-service\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (c:\project\outbox-service\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\project\outbox-service\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
.Debug: internal, implementation, error
    Error: Could not upload.
    at Object.exports.create (c:\project\outbox-service\node_modules\boom\lib\index.js:21:17)
    at Object.exports.internal (c:\project\outbox-service\node_modules\boom\lib\index.js:262:99)
    at Object.exports.badImplementation (c:\project\outbox-service\node_modules\boom\lib\index.js:298:23)
    at Object.module.exports.boom.badImplementation (c:\project\outbox-service\src\server-util.js:25:26)
    at c:\project\outbox-service\src\uploader-route.js:60:39
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at tryCatcher (c:\project\outbox-service\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (c:\project\outbox-service\node_modules\bluebird\js\main\promise.js:503:31)
    at Promise._settlePromiseAt (c:\project\outbox-service\node_modules\bluebird\js\main\promise.js:577:18)
    at Promise._settlePromises (c:\project\outbox-service\node_modules\bluebird\js\main\promise.js:693:14)
    at Async._drainQueue (c:\project\outbox-service\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (c:\project\outbox-service\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\project\outbox-service\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
.

7 tests complete
Test duration: 81 ms
No global variable leaks detected

**Comment by epikhighs** [comment]
Nm.  I finally figured it out.

In the server options (http://hapijs.com/api/8.8.1#new-serveroptions) you can set the debug flag to false.  Was driving me nuts for a few days :)
