### ISSUE TITLE
Filter duplicate stacks from error output

### ISSUE THREAD

**Issue by geek** [hapijs/lab#467]
When there is an error in the before/after we can remove duplicates from the output to reduce the amount of noise.  For example:

```
Test script errors:

Multiple callbacks or thrown errors received in test "Before example error emitted in beforeEach" (error): Uncaught, unspecified "error" event.
      at DestroyableTransform.emit (events.js:66:23)
      at emitErr (/Users/tjmehta/Developer/+lab/lab-test/lab-master/test-master.js:43:16)
      at /Users/tjmehta/Developer/+lab/lab-test/lab-master/test-master.js:19:7
      at processImmediate [as _immediateCallback] (timers.js:354:15)

Multiple callbacks or thrown errors received in test "Before each example error emitted in beforeEach" (done)
      at /Users/tjmehta/Developer/+lab/lab-test/lab-master/test-master.js:20:7
      at processImmediate [as _immediateCallback] (timers.js:354:15)

Multiple callbacks or thrown errors received in test "Before example error emitted in beforeEach" (error): Uncaught, unspecified "error" event.
      at DestroyableTransform.emit (events.js:66:23)
      at emitErr (/Users/tjmehta/Developer/+lab/lab-test/lab-master/test-master.js:43:16)
      at /Users/tjmehta/Developer/+lab/lab-test/lab-master/test-master.js:19:7
      at processImmediate [as _immediateCallback] (timers.js:354:15)

Multiple callbacks or thrown errors received in test "Before each example error emitted in test" (error): Uncaught, unspecified "error" event.
      at DestroyableTransform.emit (events.js:66:23)
      at emitErr (/Users/tjmehta/Developer/+lab/lab-test/lab-master/test-master.js:43:16)
      at /Users/tjmehta/Developer/+lab/lab-test/lab-master/test-master.js:39:7
      at processImmediate [as _immediateCallback] (timers.js:354:15)

Multiple callbacks or thrown errors received in test "Before example error emitted in test" (error)
      at Domain.emit (events.js:95:17)
      at DestroyableTransform.emit (events.js:70:21)
      at emitErr (/Users/tjmehta/Developer/+lab/lab-test/lab-master/test-master.js:43:16)
      at /Users/tjmehta/Developer/+lab/lab-test/lab-master/test-master.js:39:7
      at processImmediate [as _immediateCallback] (timers.js:354:15)
```

Can be filtered down to:

```
Test script errors:

Multiple callbacks or thrown errors received in test "Before example error emitted in beforeEach" (error): Uncaught, unspecified "error" event.
      at DestroyableTransform.emit (events.js:66:23)
      at emitErr (/Users/tjmehta/Developer/+lab/lab-test/lab-master/test-master.js:43:16)
      at /Users/tjmehta/Developer/+lab/lab-test/lab-master/test-master.js:19:7
      at processImmediate [as _immediateCallback] (timers.js:354:15)

Multiple callbacks or thrown errors received in test "Before each example error emitted in beforeEach" (done)
      at /Users/tjmehta/Developer/+lab/lab-test/lab-master/test-master.js:20:7
      at processImmediate [as _immediateCallback] (timers.js:354:15)

Multiple callbacks or thrown errors received in test "Before each example error emitted in test" (error): Uncaught, unspecified "error" event.
      at DestroyableTransform.emit (events.js:66:23)
      at emitErr (/Users/tjmehta/Developer/+lab/lab-test/lab-master/test-master.js:43:16)
      at /Users/tjmehta/Developer/+lab/lab-test/lab-master/test-master.js:39:7
      at processImmediate [as _immediateCallback] (timers.js:354:15)

Multiple callbacks or thrown errors received in test "Before example error emitted in test" (error)
      at Domain.emit (events.js:95:17)
      at DestroyableTransform.emit (events.js:70:21)
      at emitErr (/Users/tjmehta/Developer/+lab/lab-test/lab-master/test-master.js:43:16)
      at /Users/tjmehta/Developer/+lab/lab-test/lab-master/test-master.js:39:7
      at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by geek** [comment]
Closing, I am not making this a priority to implement.
