### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by kgraves** [hapijs/lab#481]
Hey guys,

I'm new to lab and wanted to try it on a new project, but am getting the following error when trying to run:
```
/home/kg/Documents/gits/hangry-js/node_modules/lab/lib/cli.js:5
const Fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/kg/Documents/gits/hangry-js/node_modules/lab/bin/lab:5:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! Test failed.  See above for more details.
```

My env is as follows:
- node: 0.12.1
- npm: 2.11.2

My package.json is as follows:
```json
  "scripts": {
    "test": "lab -a chai -t 100 ./test"
  },
  "dependencies": {
    "cheerio": "0.19.0",
    "moment": "2.10.6",
    "request": "2.65.0"
  },
  "devDependencies": {
    "chai": "3.4.0",
    "lab": "7.2.0",
    "sinon": "1.17.2"
  },
```

The only thing I could think of is that the version of node I'm running (v0.12.1) doesn't support what it's complaining about. Is node v0.12.1 not compatible with lab? According to [this](https://nodejs.org/en/download/releases/) it was released in March of this year.

**Comment by dennismonsewicz** [comment]
:+1: I'm getting the same error

**Comment by simon-p-r** [comment]
Install node version 4+, [here](https://github.com/hapijs/lab/blob/master/package.json#L11) it shows which version of node lab is compatible with.

**Comment by kgraves** [comment]
Ok, sounds good. Thanks for the input @simon-p-r

**Comment by simon-p-r** [comment]
:+1:

**Comment by kgraves** [comment]
I just wanted to follow up on this. I installed node v5.0.0 and everything works as expected. Thanks again.

**Comment by geek** [comment]
@kgraves good deal!

**Comment by dennismonsewicz** [comment]
Anyway to fix this with older versions of Node? I am running Lab v5.11 with Node v0.12.9

**Comment by geek** [comment]
@dennismonsewicz with babel?  lab 6.x.x should support node 0.10 and 0.12

**Comment by dennismonsewicz** [comment]
@geek this is the error I keep getting:

```
$ lab -T node_modules/lab-babel -S project-x/test/src/utils.js
/Users/dmonsewicz/.nvm/versions/node/v0.12.9/lib/node_modules/lab/lib/cli.js:5
const Fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/dmonsewicz/.nvm/versions/node/v0.12.9/lib/node_modules/lab/bin/lab:5:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

I have `babel-loader (v5.3.1)`, `babel (v5.8.20)`, `babel-core (v5.0.0)`, and `lab-babel (v1.1.1)`

**Comment by geek** [comment]
@dennismonsewicz double check that you are running the correct version of lab.  Look in your node_modules and also verify you don't have a different version installed globally.  The line in the stack trace refers to a more recent version https://github.com/hapijs/lab/blob/master/lib/cli.js#L5 compared to the v6.0.0 file: https://github.com/hapijs/lab/blob/fa222f8997e1444f0be6489e25f6408853fbe207/lib/cli.js#L5
