### ISSUE TITLE
Assertion causes error - Cannot check load when sampler is not started

### ISSUE THREAD

**Issue by salimkapadia** [hapijs/lab#535]
Hello,

I updated my hapijs project to the latest version of all packages identified in packages.json. When I run a single unit test using lab, I get the following error:

> Cannot check load when sampler is not started

From the console.log statements, it is not even hitting my route handler. 
 
```
//server.js
'use strict';

/**
 * Dependencies.
 */
const Hapi        = require('hapi');
const config      = require('./config/config');
const routes      = require('./routes');

const server = new Hapi.Server({
	cache: config.api.options.cache.engine,
	load: {
        	sampleInterval: 1000
	}
});

server.connection({
	host:config.api.host,
	port: Number(config.api.port),
});

server.register([
		require('vision'),
		require('inert'),
		{ register: require('bell') },
		{ register: require('lout') },
		{ register: require('hapi-auth-cookie') },
		{ register: require('./plugins/mailer/'), options: {
				apiKey: "",
				apiHost: "https://mandrillapp.com/api/1.0/",
		}}
	], function(err) {}
);

// Add configured routes to the server routes
for (var tmp in routes){
	server.route(routes[tmp]);
};

// If the script is being required as a module by another script, don’t start the server.
if (!module.parent)
{
	server.start(function() {
        console.log("Hapi server started @ " + server.info.ui);y
    });
}

// Make the server available as the top-level export of this module.
module.exports = server;

//========================================================
//controllers/authController.js
var models = require('../database');
var config = require('../config/config');
var	Boom = require('boom');
var	Joi = require('job');

// private internal functions
var internals = {};

exports.login = {
	tags: ['auth', 'login'],
	description: "App login endpoint with cookie session init",
	auth: {
		mode: 'try',
		strategy: 'session'
	},
	plugins: {
		'hapi-auth-cookie': {
			redirectTo: false
		}
	},	
	handler: function (request, reply) {
		console.log('hello')
		request.auth.session.set(request.pre.user);
		return reply([]);
	}
};

//========================================================
//test/controllers/authController.js
	var Lab = require("lab");
	var Code = require('code');   // assertion library
	var server = require("../../");
	var models = require('../../database');

	// Test shortcuts
	var lab = exports.lab = Lab.script();

	lab.experiment("method:post, url:/auth/login ", function() {
		lab.test("Login with an invalid network", function(done) {
			var options = {
				method: "post",
				url: "/auth/login",
				payload:
				{
					network: "yahoo",
					email: "testemail@yahoo.com",
					password: "test password
				}
			};

			server.inject(options, function(response) {
				console.log(response);
				var result = response.result;
				Code.expect(response.statusCode).to.equal(400);
				done();
			});
		});
	});

//========================================================
// lab test/controllers/authController.js 
Failed tests:

  1) method:post, url:/auth/login  Login with an invalid network:

      Cannot check load when sampler is not started

      at Object.exports.contain.exports.reachTemplate.exports.assert.condition [as assert] (/node_modules/hapi/node_modules/hoek/lib/index.js:732:11)
      at internals.Policy.check (/node_modules/hapi/node_modules/heavy/lib/index.js:116:10)
      at /node_modules/hapi/lib/connection.js:233:37
      at Object.internals.Request.internals.Response.writeHead.internals.finish.exports.inject (/node_modules/hapi/node_modules/shot/lib/index.js:288:5)
      at internals.Connection._init.internals.Connection._start.internals.Connection._stop.internals.Connection._dispatch.internals.Connection.inject.callback [as inject] (/node_modules/hapi/lib/connection.js:286:10)
      at module.exports.internals.Plugin.internals.Plugin.register.internals.Plugin.inject (/node_modules/hapi/lib/plugin.js:477:32)
      at /test/controllers/authController.js:21:11
      at Immediate._onImmediate (/usr/local/lib/node_modules/lab/lib/runner.js:561:17)
      at processImmediate [as _immediateCallback] (timers.js:383:17)

```"

**Comment by salimkapadia** [comment]
I updated server.js to the following:
```
if (!module.parent)
{
	server.start((err) => {
		console.log(err);
		console.log("Hapi server started @ " + server.info.ui);
	});
}
```
and when I run:

> node server.js

I get the following:

node index.js 

> { [Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
>   code: 'ECONNREFUSED',
>   errno: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '127.0.0.1',
>   port: 6379 }
> Hapi server started @ http://127.0.0.1:80 

This would probably explain why the server is not starting even though it says it started.
I ran this:

> netstat -nn  | grep LIS

and I don't see anything listening on that port. This leads me to believe that the above console.log that says that the sever has started is incorrect ?

**Comment by geek** [comment]
Closing this issue... for hapi help please look here: http://hapijs.com/help

@salimkapadia don't do any of the module.parent stuff and make sure you have a connection started with the correct port. http://hapijs.com/tutorials
