### ISSUE TITLE
error: unknown option with lab@10.2 and lab@10.3

### ISSUE THREAD

**Issue by 2color** [hapijs/lab#547]
Hey,

I've been getting the following error:
```
$lab -v test

  error: unknown option `-v'
```
This happens with most options that I pass(`-C`, `-s`)

I tried upgrading to version 10.3 however the problem persists.

Interestingly `lab -V` seems to work and outputs as expected `10.3.0`.

I am using node `v4.4.0`

**Comment by geek** [comment]
@2color is this installed globally?  I like to install locally and then will sometimes call the lab binary directly or `node node_modules/.bin/lab`

**Comment by 2color** [comment]
@geek I tried both installing locally and globally.

```
node node_modules/.bin/lab -C

  error: unknown option `-C'
```

**Comment by geek** [comment]
Can you run `npm ls` and paste it here.  I want to make sure that the dependencies are all correct, particularly `bossy`

**Comment by 2color** [comment]
There you go: 
```
├── abbrev@1.0.7
├── acorn@3.0.4
├─┬ acorn-jsx@2.0.1
│ └── acorn@2.7.0
├── align-text@0.1.4
├── amdefine@1.0.0
├── ammo@1.0.1
├── ansi-escapes@1.2.0
├── ansi-regex@2.0.0
├── ansi-styles@2.2.0
├── anymatch@1.3.0
├── argparse@1.0.6
├── arr-diff@2.0.0
├── arr-flatten@1.0.1
├── array-find-index@1.0.1
├── array-union@1.0.1
├── array-uniq@1.0.2
├── array-unique@0.2.1
├── arrify@1.0.1
├── asn1@0.2.3
├── assert-plus@0.2.0
├── async@1.5.2
├── async-each@1.0.0
├── aws-sign2@0.6.0
├─┬ aws4@1.3.2
│ └── lru-cache@4.0.0
├── babel-cli@6.6.5
├── babel-code-frame@6.6.5
├─┬ babel-core@6.6.5
│ └── minimatch@2.0.10
├── babel-generator@6.6.5
├── babel-helper-call-delegate@6.6.5
├── babel-helper-define-map@6.6.5
├── babel-helper-function-name@6.6.0
├── babel-helper-get-function-arity@6.6.5
├── babel-helper-hoist-variables@6.6.5
├── babel-helper-optimise-call-expression@6.6.0
├── babel-helper-regex@6.6.5
├── babel-helper-replace-supers@6.6.5
├── babel-helpers@6.6.0
├── babel-messages@6.6.5
├── babel-plugin-check-es2015-constants@6.6.5
├── babel-plugin-syntax-async-functions@6.5.0
├── babel-plugin-transform-es2015-arrow-functions@6.5.2
├── babel-plugin-transform-es2015-block-scoped-functions@6.6.5
├── babel-plugin-transform-es2015-block-scoping@6.6.5
├── babel-plugin-transform-es2015-classes@6.6.5
├── babel-plugin-transform-es2015-computed-properties@6.6.5
├── babel-plugin-transform-es2015-destructuring@6.6.5
├── babel-plugin-transform-es2015-duplicate-keys@6.6.4
├── babel-plugin-transform-es2015-for-of@6.6.0
├── babel-plugin-transform-es2015-function-name@6.5.0
├── babel-plugin-transform-es2015-literals@6.5.0
├── babel-plugin-transform-es2015-modules-commonjs@6.6.5
├── babel-plugin-transform-es2015-object-super@6.6.5
├── babel-plugin-transform-es2015-parameters@6.6.5
├── babel-plugin-transform-es2015-shorthand-properties@6.5.0
├── babel-plugin-transform-es2015-spread@6.6.5
├── babel-plugin-transform-es2015-sticky-regex@6.5.0
├── babel-plugin-transform-es2015-template-literals@6.6.5
├── babel-plugin-transform-es2015-typeof-symbol@6.6.0
├── babel-plugin-transform-es2015-unicode-regex@6.5.0
├── babel-plugin-transform-regenerator@6.6.5
├── babel-plugin-transform-strict-mode@6.6.5
├─┬ babel-polyfill@6.6.1
│ └── core-js@2.1.3
├── babel-preset-es2015@6.6.0
├── babel-regenerator-runtime@6.5.0
├─┬ babel-register@6.6.5
│ └── core-js@2.1.3
├── babel-runtime@5.8.35
├── babel-template@6.6.5
├── babel-traverse@6.6.5
├── babel-types@6.6.5
├── babylon@6.6.5
├── balanced-match@0.3.0
├── bin-version@1.0.4
├─┬ bin-version-check@2.1.0
│ ├── minimist@1.2.0
│ └── semver@4.3.6
├── binary-extensions@1.4.0
├─┬ bl@1.0.3
│ └── readable-stream@2.0.5
├── bluebird@3.3.4
├─┬ boom@3.1.2 invalid
│ └── hoek@3.0.4
├── bossy@1.0.3
├── brace-expansion@1.1.3
├── braces@1.8.3
├── builtin-modules@1.1.1
├── caller-path@0.1.0
├── callsites@0.2.0
├── camelcase@2.1.0
├── camelcase-keys@2.0.0
├── caseless@0.11.0
├── center-align@0.1.3
├── chalk@1.1.1
├── chokidar@1.4.3
├── cli-cursor@1.0.2
├── cli-width@2.1.0
├─┬ cliui@2.1.0
│ └── wordwrap@0.0.2
├─┬ code@2.1.0
│ └── hoek@3.0.4
├── code-point-at@1.0.0
├── color-convert@1.0.0
├── combined-stream@1.0.5
├── commander@2.9.0
├── concat-map@0.0.1
├─┬ concat-stream@1.5.1
│ └── readable-stream@2.0.5
├── configstore@1.4.0
├── console-trace@0.2.1 extraneous
├── convert-source-map@1.2.0
├── core-js@1.2.6
├── core-util-is@1.0.2
├── cryptiles@2.0.5
├── d@0.1.1
├─┬ dashdash@1.13.0
│ └── assert-plus@1.0.0
├── debug@2.2.0
├── debug-trace@0.2.4 extraneous
├── decamelize@1.2.0
├── deep-extend@0.4.1
├── deep-is@0.1.3
├── del@2.2.0
├── delayed-stream@1.0.0
├─┬ detect-indent@3.0.1
│ └── minimist@1.2.0
├── diff@2.2.1
├─┬ doctrine@1.2.0
│ ├── esutils@1.1.6
│ └── isarray@1.0.0
├── duplexer@0.1.1
├─┬ duplexify@3.4.3
│ └── readable-stream@2.0.5
├── ecc-jsbn@0.1.1
├── ejs@2.4.1 extraneous
├── end-of-stream@1.0.0
├── error-ex@1.3.0
├── es5-ext@0.10.11
├── es6-iterator@2.0.0
├── es6-map@0.1.3
├── es6-promise@3.1.2
├── es6-set@0.1.4
├── es6-symbol@3.0.2
├── es6-weak-map@2.0.1
├── escape-string-regexp@1.0.5
├── escope@3.5.0
├─┬ eslint@2.3.0
│ ├── glob@6.0.4
│ ├── lodash@4.6.1
│ └── user-home@2.0.0
├── eslint-config-hapi@9.1.0
├── eslint-plugin-hapi@4.0.0
├── espree@3.1.1
├── esprima@2.7.2
├── esrecurse@4.0.0
├── estraverse@4.1.1
├── esutils@2.0.2
├── event-emitter@0.3.4
├── event-stream@3.3.2
├── exit-hook@1.1.1
├── expand-brackets@0.1.4
├── expand-range@1.8.1
├── extend@3.0.0
├── extglob@0.3.2
├── extsprintf@1.0.2
├── fast-levenshtein@1.1.3
├── figures@1.4.0
├── file-entry-cache@1.2.4
├── filename-regex@2.0.0
├── fill-range@2.2.3
├─┬ find-up@1.1.2
│ └── path-exists@2.1.0
├── find-versions@1.2.1
├── flat@2.0.0 extraneous
├── flat-cache@1.0.10
├── for-in@0.1.4
├── for-own@0.1.3
├── forever-agent@0.6.1
├── form-data@1.0.0-rc3
├── from@0.1.3
├── fs-readdir-recursive@0.1.2
├─┬ fsevents@1.0.8
│ ├── ansi@0.3.1
│ ├── ansi-regex@2.0.0
│ ├── ansi-styles@2.1.0
│ ├── are-we-there-yet@1.0.6
│ ├── asn1@0.2.3
│ ├── assert-plus@0.2.0
│ ├── async@1.5.2
│ ├── aws-sign2@0.6.0
│ ├─┬ aws4@1.2.1
│ │ └── lru-cache@2.7.3
│ ├── bl@1.0.2
│ ├── block-stream@0.0.8
│ ├── boom@2.10.1
│ ├── caseless@0.11.0
│ ├── chalk@1.1.1
│ ├── combined-stream@1.0.5
│ ├── commander@2.9.0
│ ├── core-util-is@1.0.2
│ ├── cryptiles@2.0.5
│ ├── dashdash@1.12.2
│ ├── debug@2.2.0
│ ├── deep-extend@0.4.1
│ ├── delayed-stream@1.0.0
│ ├── delegates@1.0.0
│ ├── ecc-jsbn@0.1.1
│ ├── escape-string-regexp@1.0.4
│ ├── extend@3.0.0
│ ├── extsprintf@1.0.2
│ ├── forever-agent@0.6.1
│ ├── form-data@1.0.0-rc3
│ ├── fstream@1.0.8
│ ├─┬ fstream-ignore@1.0.3
│ │ └─┬ minimatch@3.0.0
│ │   └─┬ brace-expansion@1.1.2
│ │     ├── balanced-match@0.3.0
│ │     └── concat-map@0.0.1
│ ├── gauge@1.2.5
│ ├── generate-function@2.0.0
│ ├── generate-object-property@1.2.0
│ ├── graceful-fs@4.1.3
│ ├── graceful-readlink@1.0.1
│ ├── har-validator@2.0.6
│ ├── has-ansi@2.0.0
│ ├── has-unicode@2.0.0
│ ├── hawk@3.1.3
│ ├── hoek@2.16.3
│ ├── http-signature@1.1.1
│ ├── inherits@2.0.1
│ ├── ini@1.3.4
│ ├── is-my-json-valid@2.12.4
│ ├── is-property@1.0.2
│ ├── is-typedarray@1.0.0
│ ├── isarray@0.0.1
│ ├── isstream@0.1.2
│ ├── jodid25519@1.0.2
│ ├── jsbn@0.1.0
│ ├── json-schema@0.2.2
│ ├── json-stringify-safe@5.0.1
│ ├── jsonpointer@2.0.0
│ ├── jsprim@1.2.2
│ ├── lodash._basetostring@3.0.1
│ ├── lodash._createpadding@3.6.1
│ ├── lodash._root@3.0.0
│ ├── lodash.pad@3.3.0
│ ├── lodash.padleft@3.1.1
│ ├── lodash.padright@3.1.1
│ ├── lodash.repeat@3.2.0
│ ├── mime-db@1.21.0
│ ├── mime-types@2.1.9
│ ├── minimist@0.0.8
│ ├── mkdirp@0.5.1
│ ├── ms@0.7.1
│ ├─┬ node-pre-gyp@0.6.21
│ │ └─┬ nopt@3.0.6
│ │   └── abbrev@1.0.7
│ ├── node-uuid@1.4.7
│ ├── npmlog@2.0.2
│ ├── oauth-sign@0.8.1
│ ├── once@1.3.3
│ ├── pinkie@2.0.4
│ ├── pinkie-promise@2.0.0
│ ├── process-nextick-args@1.0.6
│ ├── qs@6.0.2
│ ├─┬ rc@1.1.6
│ │ └── minimist@1.2.0
│ ├── readable-stream@2.0.5
│ ├── request@2.69.0
│ ├─┬ rimraf@2.5.1
│ │ └─┬ glob@6.0.4
│ │   ├─┬ inflight@1.0.4
│ │   │ └── wrappy@1.0.1
│ │   ├── inherits@2.0.1
│ │   ├─┬ minimatch@3.0.0
│ │   │ └─┬ brace-expansion@1.1.2
│ │   │   ├── balanced-match@0.3.0
│ │   │   └── concat-map@0.0.1
│ │   ├─┬ once@1.3.3
│ │   │ └── wrappy@1.0.1
│ │   └── path-is-absolute@1.0.0
│ ├── semver@5.1.0
│ ├── sntp@1.0.9
│ ├── sshpk@1.7.3
│ ├── string_decoder@0.10.31
│ ├── stringstream@0.0.5
│ ├── strip-ansi@3.0.0
│ ├── strip-json-comments@1.0.4
│ ├── supports-color@2.0.0
│ ├── tar@2.2.1
│ ├── tar-pack@3.1.3
│ ├── tough-cookie@2.2.1
│ ├── tunnel-agent@0.4.2
│ ├── tweetnacl@0.13.3
│ ├── uid-number@0.0.6
│ ├── util-deprecate@1.0.2
│ ├── verror@1.3.6
│ ├── wrappy@1.0.1
│ └── xtend@4.0.1
├── generate-function@2.0.0
├── generate-object-property@1.2.0
├── get-stdin@4.0.1
├─┬ github4@0.5.4
│ ├─┬ follow-redirects@0.0.7
│ │ └── stream-consume@0.1.0
│ ├─┬ https-proxy-agent@1.0.0
│ │ └─┬ agent-base@2.0.1
│ │   └── semver@5.0.3
│ └── mime@1.3.4
├── glob@5.0.15
├── glob-base@0.3.0
├── glob-parent@2.0.0
├── globals@8.18.0
├─┬ globby@4.0.0
│ └── glob@6.0.4
├─┬ good@6.6.0
│ ├── isemail@1.2.0
│ ├── joi@6.10.1
│ └── topo@1.1.0
├─┬ good-console@5.3.1
│ └── moment@2.11.2
├── good-squeeze@2.1.0
├─┬ got@3.3.1
│ └── object-assign@3.0.0
├── graceful-fs@4.1.3
├── graceful-readlink@1.0.1
├─┬ handlebars@4.0.5
│ └── source-map@0.4.4
├─┬ hapi@13.1.0
│ ├── accept@2.1.0
│ ├── ammo@2.0.0
│ ├── boom@3.1.2
│ ├── call@3.0.0
│ ├─┬ catbox@7.1.0
│ │ └── joi@7.3.0
│ ├── catbox-memory@2.0.1
│ ├── cryptiles@3.0.0
│ ├─┬ heavy@4.0.0
│ │ └── joi@7.3.0
│ ├── hoek@3.0.4
│ ├── iron@4.0.0
│ ├── items@2.0.0
│ ├── kilt@2.0.0
│ ├── mimos@3.0.0
│ ├── peekaboo@2.0.0
│ ├── shot@3.0.1
│ ├─┬ statehood@4.0.0
│ │ └── joi@7.3.0
│ └─┬ subtext@4.0.0
│   ├── content@3.0.0
│   ├─┬ pez@2.0.1
│   │ ├── b64@3.0.0
│   │ └─┬ nigel@2.0.0
│   │   └── vise@2.0.0
│   └── wreck@7.0.2
├── hapi-capitalize-modules@1.1.4
├── hapi-for-you@1.0.0
├── hapi-scope-start@2.1.1
├── har-validator@2.0.6
├── has-ansi@2.0.0
├── hawk@3.1.3
├── hoek@2.16.3
├── home-or-tmp@1.0.0
├── hosted-git-info@2.1.4
├── http-signature@1.1.1
├── ignore@2.2.19
├── ignore-by-default@1.0.1
├── imurmurhash@0.1.4
├─┬ indent-string@2.1.0
│ └── repeating@2.0.0
├─┬ inert@3.2.0
│ ├── isemail@1.2.0
│ ├── joi@6.10.1
│ └── topo@1.1.0
├── infinity-agent@2.0.3
├── inflight@1.0.4
├── inherits@2.0.1
├── ini@1.3.4
├─┬ inquirer@0.12.0
│ └── lodash@4.6.1
├── invariant@2.2.0
├── is-arrayish@0.2.1
├── is-binary-path@1.0.1
├── is-buffer@1.1.3
├── is-builtin-module@1.0.0
├── is-dotfile@1.0.2
├── is-equal-shallow@0.1.3
├── is-extendable@0.1.1
├── is-extglob@1.0.0
├── is-finite@1.0.1
├── is-fullwidth-code-point@1.0.0
├── is-glob@2.0.1
├── is-integer@1.0.6
├── is-my-json-valid@2.13.1
├── is-npm@1.0.0
├── is-number@2.1.0
├── is-path-cwd@1.0.0
├── is-path-in-cwd@1.0.0
├── is-path-inside@1.0.0
├── is-primitive@2.0.0
├── is-property@1.0.2
├── is-redirect@1.0.0
├── is-resolvable@1.0.0
├── is-stream@1.0.1
├── is-typedarray@1.0.0
├── is-utf8@0.2.1
├── isarray@0.0.1
├── isemail@2.1.0
├── isobject@2.0.0
├── isstream@0.1.2
├── items@1.1.1
├── jodid25519@1.0.2
├─┬ joi@8.0.4
│ └── hoek@3.0.4
├── js-tokens@1.0.2
├── js-yaml@3.5.3
├── jsbn@0.1.0
├── jsesc@0.5.0
├── json-schema@0.2.2
├── json-stable-stringify@1.0.1
├── json-stringify-safe@5.0.1
├── json5@0.4.0
├── jsonify@0.0.0
├── jsonpointer@2.0.0
├── jsprim@1.2.2
├── kind-of@3.0.2
├─┬ lab@10.3.0
│ ├─┬ eslint@2.4.0
│ │ ├─┬ escope@3.6.0
│ │ │ └─┬ esrecurse@4.1.0
│ │ │   └── estraverse@4.1.1
│ │ ├── estraverse@4.2.0
│ │ ├── glob@6.0.4
│ │ └── user-home@2.0.0
│ ├── hoek@3.0.4
│ ├── items@2.0.0
│ └─┬ source-map-support@0.4.0
│   └── source-map@0.1.32
├── latest-version@1.0.1
├── lazy-cache@1.0.3
├── left-pad@0.0.3
├── levn@0.3.0
├── line-numbers@0.2.0
├── load-json-file@1.1.0
├── lodash@4.6.1 invalid
├── lodash._baseassign@3.2.0
├── lodash._basecopy@3.0.1
├── lodash._bindcallback@3.0.1
├── lodash._createassigner@3.1.1
├── lodash._getnative@3.9.1
├── lodash._isiterateecall@3.0.9
├── lodash.assign@3.2.0
├── lodash.defaults@3.1.2
├── lodash.isarguments@3.0.8
├── lodash.isarray@3.0.4
├── lodash.keys@3.1.2
├── lodash.restparam@3.6.1
├── log-symbols@1.0.2
├── longest@1.0.1
├── loose-envify@1.1.0
├── loud-rejection@1.3.0
├── lowercase-keys@1.0.0
├── lru-cache@2.7.3
├── map-obj@1.0.1
├── map-stream@0.1.0
├─┬ meow@3.7.0
│ └── minimist@1.2.0
├── micromatch@2.3.7
├── mime-db@1.22.0
├── mime-types@2.1.10
├── minimatch@3.0.0
├── minimist@0.0.8
├── mkdirp@0.5.1
├── moment@2.12.0
├── ms@0.7.1
├── mute-stream@0.0.5
├── nan@2.2.0
├── nested-error-stacks@1.0.2
├── no-arrowception@1.0.0
├── node-uuid@1.4.7
├── nodemon@1.9.1
├── nopt@1.0.10
├── normalize-package-data@2.3.5
├── normalize-path@2.0.1
├── number-is-nan@1.0.0
├── oauth-sign@0.8.1
├── object-assign@4.0.1
├── object.omit@2.0.0
├── octonode@0.7.4 extraneous
├── once@1.3.3
├── onetime@1.1.0
├─┬ optimist@0.6.1
│ └── wordwrap@0.0.3
├── optionator@0.8.1
├── os-homedir@1.0.1
├── os-tmpdir@1.0.1
├── osenv@0.1.3
├── output-file-sync@1.1.1
├── package-json@1.2.0
├── parse-glob@3.0.4
├── parse-json@2.2.0
├── path-exists@1.0.0
├── path-is-absolute@1.0.0
├── path-is-inside@1.0.1
├── path-type@1.1.0
├── pause-stream@0.0.11
├── pify@2.3.0
├── pinkie@2.0.4
├── pinkie-promise@2.0.0
├── pluralize@1.2.1
├─┬ pm2@1.0.2
│ ├─┬ cli-table@0.3.1
│ │ └── colors@1.0.3
│ ├── coffee-script@1.10.0
│ ├─┬ cron@1.1.0
│ │ └── moment-timezone@0.3.1
│ ├── eventemitter2@0.4.14
│ ├── ikt@0.0.0 (git+http://ikt.pm2.io/ikt.git#3325a3e39a502418dc2e2e4bf21529cbbde96228)
│ ├── moment@2.11.2
│ ├─┬ nssocket@0.6.0
│ │ └── lazy@1.0.11
│ ├── pidusage@1.0.1
│ ├─┬ pm2-axon@2.0.9
│ │ ├── amp@0.3.1
│ │ ├── amp-message@0.1.2
│ │ ├── configurable@0.0.1
│ │ └── escape-regexp@0.0.1
│ ├─┬ pm2-axon-rpc@0.3.6
│ │ └─┬ commander@1.0.5
│ │   └── keypress@0.1.0
│ ├─┬ pm2-deploy@0.2.1
│ │ ├── async@1.4.2
│ │ └── tv4@1.0.18
│ ├─┬ pm2-multimeter@0.1.2
│ │ └── charm@0.1.2
│ ├── pmx@0.6.1
│ ├── shelljs@0.6.0
│ ├─┬ source-map-support@0.4.0
│ │ └── source-map@0.1.32
│ └─┬ vizion@0.2.12
│   └── async@0.9.0
├── prelude-ls@1.1.2
├── prepend-http@1.0.3
├── preserve@0.2.0
├── private@0.1.6
├── process-nextick-args@1.0.6
├── progress@1.1.8
├── ps-tree@1.0.1
├── pseudomap@1.0.2
├── qs@6.0.2
├── randomatic@1.1.5
├─┬ rc@1.1.6
│ └── minimist@1.2.0
├─┬ read-all-stream@3.1.0
│ └── readable-stream@2.0.5
├── read-json-sync@1.1.1
├── read-pkg@1.1.0
├── read-pkg-up@1.0.1
├── readable-stream@1.0.33
├─┬ readdirp@2.0.0
│ ├── minimatch@2.0.10
│ └── readable-stream@2.0.5
├── readline2@1.0.1
├── redent@1.0.0
├── regenerate@1.2.1
├── regex-cache@0.4.2
├── regexpu-core@1.0.0
├── registry-url@3.0.3
├── regjsgen@0.2.0
├── regjsparser@0.1.5
├── repeat-element@1.1.2
├── repeat-string@1.5.4
├── repeating@1.1.3
├── request@2.69.0
├── require-uncached@1.0.2
├── resolve@1.1.7
├── resolve-from@1.0.1
├── restore-cursor@1.0.1
├── right-align@0.1.3
├─┬ rimraf@2.5.2
│ └── glob@7.0.3
├── run-async@0.1.0
├── rx-lite@3.1.2
├── semver@5.1.0
├── semver-diff@2.1.0
├── semver-regex@1.0.0
├── semver-truncate@1.1.0
├── shebang-regex@1.0.0
├── shelljs@0.5.3
├── signal-exit@2.1.2
├── slash@1.0.0
├── slice-ansi@0.0.4
├── slide@1.1.6
├── sntp@1.0.9
├── source-map@0.5.3
├─┬ source-map-support@0.2.10
│ └── source-map@0.1.32
├── spdx-correct@1.0.2
├── spdx-exceptions@1.0.4
├── spdx-expression-parse@1.0.2
├── spdx-license-ids@1.2.0
├── split@0.3.3
├── sprintf-js@1.0.3
├── sshpk@1.7.4
├── stream-combiner@0.0.4
├── string-length@1.0.1
├── string-width@1.0.1
├── string_decoder@0.10.31
├── stringstream@0.0.5
├── strip-ansi@3.0.1
├── strip-bom@2.0.0
├── strip-indent@1.0.1
├── strip-json-comments@1.0.4
├── supports-color@2.0.0
├─┬ table@3.7.8
│ └── lodash@4.6.1
├── text-table@0.2.0
├── through@2.3.8
├── through2@0.6.5
├── timed-out@2.0.0
├── to-fast-properties@1.0.1
├─┬ topo@2.0.0
│ └── hoek@3.0.4
├── touch@1.0.0
├── tough-cookie@2.2.1
├── traverse@0.6.6
├── trim-newlines@1.0.0
├── trim-right@1.0.1
├── tryit@1.0.2
├── tunnel-agent@0.4.2
├── tv4@1.2.7
├── tweetnacl@0.14.1
├── type-check@0.3.2
├── typedarray@0.0.6
├─┬ uglify-js@2.6.2
│ └── async@0.2.10
├── uglify-to-browserify@1.0.2
├── undefsafe@0.0.3
├── update-notifier@0.5.0
├── user-home@1.1.1
├── util-deprecate@1.0.2
├── uuid@2.0.1
├── v8flags@2.0.11
├── validate-npm-package-license@3.0.1
├── verror@1.3.6
├── window-size@0.1.0
├── wordwrap@1.0.0
├── wrappy@1.0.1
├── wreck@6.3.0
├── write@0.2.1
├── write-file-atomic@1.1.4
├── xdg-basedir@2.0.0
├── xregexp@3.1.0
├── xtend@4.0.1
├── yallist@2.0.0
└─┬ yargs@3.10.0
  └── camelcase@1.2.1

```

**Comment by geek** [comment]
Pasting here so I have a reference...

This is the result if you create a new folder, run `npm install lab` and then `npm ls`

```sh
└─┬ lab@10.3.0
  ├─┬ bossy@1.0.3
  │ └── hoek@2.16.3
  ├── diff@2.2.2
  ├─┬ eslint@2.4.0
  │ ├─┬ chalk@1.1.1
  │ │ ├─┬ ansi-styles@2.2.0
  │ │ │ └── color-convert@1.0.0
  │ │ ├── escape-string-regexp@1.0.5
  │ │ ├── has-ansi@2.0.0
  │ │ ├── strip-ansi@3.0.1
  │ │ └── supports-color@2.0.0
  │ ├─┬ concat-stream@1.5.1
  │ │ ├── inherits@2.0.1
  │ │ ├─┬ readable-stream@2.0.6
  │ │ │ ├── core-util-is@1.0.2
  │ │ │ ├── process-nextick-args@1.0.6
  │ │ │ ├── string_decoder@0.10.31
  │ │ │ └── util-deprecate@1.0.2
  │ │ └── typedarray@0.0.6
  │ ├─┬ debug@2.2.0
  │ │ └── ms@0.7.1
  │ ├─┬ doctrine@1.2.0
  │ │ ├── esutils@1.1.6
  │ │ └── isarray@1.0.0
  │ ├─┬ es6-map@0.1.3
  │ │ ├── d@0.1.1
  │ │ ├── es5-ext@0.10.11
  │ │ ├── es6-iterator@2.0.0
  │ │ ├── es6-set@0.1.4
  │ │ ├── es6-symbol@3.0.2
  │ │ └── event-emitter@0.3.4
  │ ├─┬ escope@3.6.0
  │ │ ├── es6-weak-map@2.0.1
  │ │ └─┬ esrecurse@4.1.0
  │ │   └── estraverse@4.1.1
  │ ├── estraverse@4.2.0
  │ ├── esutils@2.0.2
  │ ├─┬ file-entry-cache@1.2.4
  │ │ ├─┬ flat-cache@1.0.10
  │ │ │ ├─┬ del@2.2.0
  │ │ │ │ ├─┬ globby@4.0.0
  │ │ │ │ │ ├─┬ array-union@1.0.1
  │ │ │ │ │ │ └── array-uniq@1.0.2
  │ │ │ │ │ └── arrify@1.0.1
  │ │ │ │ ├── is-path-cwd@1.0.0
  │ │ │ │ ├─┬ is-path-in-cwd@1.0.0
  │ │ │ │ │ └── is-path-inside@1.0.0
  │ │ │ │ ├── pify@2.3.0
  │ │ │ │ ├─┬ pinkie-promise@2.0.0
  │ │ │ │ │ └── pinkie@2.0.4
  │ │ │ │ └─┬ rimraf@2.5.2
  │ │ │ │   └── glob@7.0.3
  │ │ │ ├── graceful-fs@4.1.3
  │ │ │ ├── read-json-sync@1.1.1
  │ │ │ └── write@0.2.1
  │ │ └── object-assign@4.0.1
  │ ├─┬ glob@6.0.4
  │ │ ├─┬ inflight@1.0.4
  │ │ │ └── wrappy@1.0.1
  │ │ ├─┬ minimatch@3.0.0
  │ │ │ └─┬ brace-expansion@1.1.3
  │ │ │   ├── balanced-match@0.3.0
  │ │ │   └── concat-map@0.0.1
  │ │ └── once@1.3.3
  │ ├── globals@8.18.0
  │ ├── ignore@2.2.19
  │ ├─┬ inquirer@0.12.0
  │ │ ├── ansi-escapes@1.3.0
  │ │ ├── ansi-regex@2.0.0
  │ │ ├─┬ cli-cursor@1.0.2
  │ │ │ └─┬ restore-cursor@1.0.1
  │ │ │   ├── exit-hook@1.1.1
  │ │ │   └── onetime@1.1.0
  │ │ ├── cli-width@2.1.0
  │ │ ├── figures@1.5.0
  │ │ ├─┬ readline2@1.0.1
  │ │ │ ├─┬ code-point-at@1.0.0
  │ │ │ │ └── number-is-nan@1.0.0
  │ │ │ ├── is-fullwidth-code-point@1.0.0
  │ │ │ └── mute-stream@0.0.5
  │ │ ├── run-async@0.1.0
  │ │ ├── rx-lite@3.1.2
  │ │ ├── string-width@1.0.1
  │ │ └── through@2.3.8
  │ ├─┬ is-my-json-valid@2.13.1
  │ │ ├── generate-function@2.0.0
  │ │ ├─┬ generate-object-property@1.2.0
  │ │ │ └── is-property@1.0.2
  │ │ ├── jsonpointer@2.0.0
  │ │ └── xtend@4.0.1
  │ ├─┬ is-resolvable@1.0.0
  │ │ └── tryit@1.0.2
  │ ├─┬ js-yaml@3.5.5
  │ │ ├─┬ argparse@1.0.7
  │ │ │ └── sprintf-js@1.0.3
  │ │ └── esprima@2.7.2
  │ ├─┬ json-stable-stringify@1.0.1
  │ │ └── jsonify@0.0.0
  │ ├── lodash@4.6.1
  │ ├─┬ optionator@0.8.1
  │ │ ├── deep-is@0.1.3
  │ │ ├── fast-levenshtein@1.1.3
  │ │ ├── levn@0.3.0
  │ │ ├── prelude-ls@1.1.2
  │ │ ├── type-check@0.3.2
  │ │ └── wordwrap@1.0.0
  │ ├── path-is-absolute@1.0.0
  │ ├── path-is-inside@1.0.1
  │ ├── pluralize@1.2.1
  │ ├── progress@1.1.8
  │ ├─┬ require-uncached@1.0.2
  │ │ ├─┬ caller-path@0.1.0
  │ │ │ └── callsites@0.2.0
  │ │ └── resolve-from@1.0.1
  │ ├── resolve@1.1.7
  │ ├── shelljs@0.5.3
  │ ├── strip-json-comments@1.0.4
  │ ├─┬ table@3.7.8
  │ │ ├── bluebird@3.3.4
  │ │ ├── slice-ansi@0.0.4
  │ │ ├── tv4@1.2.7
  │ │ └── xregexp@3.1.0
  │ ├── text-table@0.2.0
  │ └─┬ user-home@2.0.0
  │   └── os-homedir@1.0.1
  ├── eslint-config-hapi@9.1.0
  ├─┬ eslint-plugin-hapi@4.0.0
  │ ├── hapi-capitalize-modules@1.1.4
  │ ├── hapi-for-you@1.0.0
  │ ├── hapi-scope-start@2.1.1
  │ └── no-arrowception@1.0.0
  ├─┬ espree@3.1.3
  │ ├── acorn@3.0.4
  │ └─┬ acorn-jsx@2.0.1
  │   └── acorn@2.7.0
  ├─┬ handlebars@4.0.5
  │ ├── async@1.5.2
  │ ├─┬ optimist@0.6.1
  │ │ └── wordwrap@0.0.3
  │ ├─┬ source-map@0.4.4
  │ │ └── amdefine@1.0.0
  │ └─┬ uglify-js@2.6.2
  │   ├── async@0.2.10
  │   ├── source-map@0.5.3
  │   ├── uglify-to-browserify@1.0.2
  │   └─┬ yargs@3.10.0
  │     ├── camelcase@1.2.1
  │     ├─┬ cliui@2.1.0
  │     │ ├─┬ center-align@0.1.3
  │     │ │ ├─┬ align-text@0.1.4
  │     │ │ │ ├─┬ kind-of@3.0.2
  │     │ │ │ │ └── is-buffer@1.1.3
  │     │ │ │ ├── longest@1.0.1
  │     │ │ │ └── repeat-string@1.5.4
  │     │ │ └── lazy-cache@1.0.3
  │     │ ├── right-align@0.1.3
  │     │ └── wordwrap@0.0.2
  │     ├── decamelize@1.2.0
  │     └── window-size@0.1.0
  ├── hoek@3.0.4
  ├── items@2.0.0
  ├── json-stringify-safe@5.0.1
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  └─┬ source-map-support@0.4.0
    └── source-map@0.1.32
```

**Comment by geek** [comment]
I recommend trying out lab in a separate folder, without the other dependencies interfering...

```sh
mkdir ~/test
cd ~/test
npm install lab
node node_modules/.bin/lab -C
```

You should get a different error about it not finding tests

**Comment by 2color** [comment]
Indeed you're right.

What shall I do to resolve this in my project?

```
➜  labtest node node_modules/.bin/lab -C
fs.js:844
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat 'test'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at path (/Users/danielnorman/workspace/labtest/node_modules/lab/lib/cli.js:62:29)
    at /Users/danielnorman/workspace/labtest/node_modules/lab/lib/cli.js:92:38
    at Array.forEach (native)
    at Object.internals.traverse.paths.forEach.testFiles [as traverse] (/Users/danielnorman/workspace/labtest/node_modules/lab/lib/cli.js:90:11)
    at Object.exports.run (/Users/danielnorman/workspace/labtest/node_modules/lab/lib/cli.js:51:31)
    at Object.<anonymous> (/Users/danielnorman/workspace/labtest/node_modules/lab/bin/lab:5:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by geek** [comment]
@2color its not a great solution, but in order to narrow down the culprit you can go into your project folder and
1. `rm -rf node_modules`
2. `npm install lab`
3. Go through each dependency in your project and `npm install _dep_` and after each check that `npm test` works, when it doesn't, then you have found the dependency culprit.
