### ISSUE TITLE
global.__$$labCov._line - Cannot read property '_line' of undefined

### ISSUE THREAD

**Issue by acavestro** [hapijs/lab#600]
Hi,
I was using Lab for running test of a project I'm working on.
I set Lab to trace the coverage (-c flag) and to exclude from that the node_modules directory (--coverage-exclude).

When I ran the test, I encoutered this strange error:

```
lab -vc ./project/test/**/*.js --coverage-exclude ./project/node_modules

/project/node_modules/tracer/node_modules/dateformat/lib/dateformat.js:18
  global.__$$labCov._line('/project/node_modules/tracer/node_modules/dateformat/lib/dateformat.js',18);var dateFormat = (function() {
                   ^

TypeError: Cannot read property '_line' of undefined
    at /project/node_modules/tracer/node_modules/dateformat/lib/dateformat.js:18:20
    at Object.<anonymous> (/project/node_modules/tracer/node_modules/dateformat/lib/dateformat.js:224:3)
    at Module._compile (module.js:409:26)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/lab/lib/coverage.js:31:36)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/project/node_modules/tracer/lib/console.js:2:161)
    at Module._compile (module.js:409:26)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/lab/lib/coverage.js:31:36)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/project/node_modules/tracer/lib/index.js:2:130)
    at Module._compile (module.js:409:26)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/lab/lib/coverage.js:31:36)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/project/lib/foolib/lib/bar.js:5:133)
    at Module._compile (module.js:409:26)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/lab/lib/coverage.js:31:36)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/project/lib/foolib/index.js:2:128)
    at Module._compile (module.js:409:26)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/lab/lib/coverage.js:31:36)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at Module.requireProxy (/project/node_modules/rewire/lib/moduleEnv.js:46:140)
    at require (internal/module.js:12:17)
    at /project/foo/bar.js:3:126
    at Object.<anonymous> (/project/foo/bar.js:797:4)
    at Module._compile (module.js:409:26)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/lab/lib/coverage.js:31:36)
    at Module.load (module.js:343:32)
    at Object.load (/project/node_modules/rewire/lib/moduleEnv.js:20:134)
    at internalRewire (/project/node_modules/rewire/lib/rewire.js:57:128)
    at rewire (/project/node_modules/rewire/lib/index.js:11:124)
    at Object.<anonymous> (/project/test/foo/bar.js:13:159)
    at Module._compile (module.js:409:26)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/lab/lib/coverage.js:31:36)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /usr/lib/node_modules/lab/lib/cli.js:111:25
    at Array.forEach (native)
    at Object.internals.traverse.paths.forEach.testFiles [as traverse] (/usr/lib/node_modules/lab/lib/cli.js:107:19)
    at Object.exports.run (/usr/lib/node_modules/lab/lib/cli.js:56:31)
    at Object.<anonymous> (/usr/lib/node_modules/lab/bin/lab:5:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

Apparently one of the project dependencies, tracer, seems to be in conflict with Lab coverage system (I think) and I don't understand how this is possible and how to fix it.

This happens only when I run the tests in a CI environment with Jenkins, but node, Lab and tracert package are at the same version, the latest:
- node v.4.4.5
- lab v10.7.1
- tracer v0.8.3

The only difference is in the OS, Linux for Jenkins env, OS X for my local env, but I can't see how this could be related.

I am looking to the Lab code to see a possible light at the end of the tunnel, but until then I hope someone could help me to this strange case.

Bye

**Comment by geek** [comment]
@acavestro if you remove the `--coverage-exclude` line and rely on the default coverage excludes does this still occur?  By default it will ignore the `test` and `node_modules` folders.

**Comment by acavestro** [comment]
@geek, thanks for you reply! Yes, it still occurs :/ In fact, I tried that flag to hope to avoid that error..

**Comment by damusix** [comment]
happens to me when requiring a local package eg: `require('../..')` and inside of a function that requires local package

```
function () {
x = require('../../thing.js');
}
```

My workaround was to manually declare the folders I wanted coverage on like so: `lab -c api/ lib/ config/` and so on.

**Comment by hueniverse** [comment]
Closing due to inactivity.
