### ISSUE TITLE
Lint appears to fail due to runtime error, but lab exits 0

### ISSUE THREAD

**Issue by devinivy** [hapijs/lab#604]
I have a library where my tests do some fancy file-renaming.  On node v5 and v6 (but not v4) lab seems to run into a runtime error during linting since it doesn't find a file that it expects to exist.  I'm sure this has to do with my fancy file-renaming.

I'm interested to resolve that particular issue, but the main problem at hand is that my tests appeared to have passed (exit 0) despite the linting error.  Here's what travis shows me on node v6 (and v5 is very similar),

```
$ npm test
> haute-couture@1.0.0 test /home/travis/build/devinivy/haute-couture
> lab -a code -t 100 -L

  .............................fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/home/travis/build/devinivy/haute-couture/test/closet/auth.off/default.js'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at processFile (/home/travis/build/devinivy/haute-couture/node_modules/eslint/lib/cli-engine.js:291:19)
    at executeOnFile (/home/travis/build/devinivy/haute-couture/node_modules/eslint/lib/cli-engine.js:676:23)
    at /home/travis/build/devinivy/haute-couture/node_modules/eslint/lib/cli-engine.js:713:13
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/home/travis/build/devinivy/haute-couture/node_modules/eslint/lib/cli-engine.js:712:18)
    at Object.exports.lint (/home/travis/build/devinivy/haute-couture/node_modules/lab/lib/linter/index.js:41:28)
    at Object.<anonymous> (/home/travis/build/devinivy/haute-couture/node_modules/lab/lib/linter/index.js:68:22)
The command "npm test" exited with 0.
```

Here's the build, if you'd like to look further into it across node versions: https://travis-ci.org/devinivy/haute-couture/jobs/137497208.

**Comment by devinivy** [comment]
I think both my issue and the lab bug make sense after looking at this line
https://github.com/hapijs/lab/blob/master/lib/runner.js#L108
```js
Items.parallel.execute({ notebook: executeScripts, lint: executeLint }, (ignoreErr, results) => {/* ... */});
```

My guess is that it's cool to ignore errors from the notebook but not those from the linter.  As for my own problem– I didn't realize the lint and the tests were run in parallel.  Makes sense a problem could arise given what I'm doing.

**Comment by geek** [comment]
This shouldn't be an issue with the latest where lint errors aren't ignored.
