### ISSUE TITLE
Failure when using lab to launch a express or hapi based project

### ISSUE THREAD

**Issue by dgonzalez** [hapijs/lab#636]
Here is the code:
```
'use strict'

const Assert = require('assert')
const request = require('request')
const Seneca = require('seneca')
const Web = require('../../')
const Express = require('express')

var server = Express()

var seneca = Seneca({log:'test'})
  .use(Web, {adapter: 'express', context: server})

var config = {
  routes: {
    pin: 'role:test,cmd:*',
    map: {
      one: true,
      two: true
    }
  }
}

seneca.act('role:web', config, (err, reply) => {
  if (err) return done(err)

  seneca.add('role:test,cmd:one', (msg, reply) => {
    reply(null, {res: 'pong!'})
  })

  seneca.add('role:test,cmd:two', (msg, reply) => {
    reply(null, {res: 'ping!'})
  })

  server.listen('5001', (err) => {
    request('http://127.0.0.1:5001/one', (err, res, body) => {
      console.log(JSON.parse(body))

      request('http://127.0.0.1:5001/two', (err, res, body) => {
        console.log(JSON.parse(body))
        process.exit()
      })
    })
  })
})
```

If we execute it with:
```
node test.js
```
Everything works smoothly.

If we execute it with lab within a test:
```
it('by default routes autoreply', (done) => {
    var server = Express()

    var config = {
      routes: {
        pin: 'role:test,cmd:*',
        map: {
          ping: true
        }
      }
    }

    var seneca = Seneca({log:'test'})
      .use(Web, {adapter: 'express', context: server})

    seneca.act('role:web', config, (err, reply) => {
      if (err) return done(err)

      seneca.add('role:test,cmd:ping', (msg, reply) => {
        reply(null, {res: 'pong!'})
      })

      server.listen('5000', (err) => {
        if (err) return done(err)

        request('http://127.0.0.1:5000/ping', (err, res, body) => {
          body = JSON.parse(body)

          expect(err).to.be.null()
          expect(body).to.be.equal({res: 'pong!'})
          done()
        })
      })
    })
  })
```
We get the following error:
```
Details: { message: 'Cannot read property \'encrypted\' of undefined',
  pattern: 'name:web,plugin:define,role:seneca,seq:2,tag:undefined',
  fn: [Function: plugin_definition],
  cb: [Function: noop],
  instance: 'Seneca/3ybl951y1vea/1473257602032/24641/3.0.0/-',
  'orig$': [TypeError: Cannot read property 'encrypted' of undefined],
  'message$': 'Cannot read property \'encrypted\' of undefined',
  plugin: {} }

Stack:
    at IncomingMessage.protocol (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/express/lib/request.js:301:30)
    at /Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:3482:28
    at arrayEach (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:522:11)
    at baseMerge (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:3479:7)
    at mergeDefaults (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:6242:9)
    at baseMergeDeep (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:3526:11)
    at /Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:3486:11
    at arrayEach (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:522:11)
    at baseMerge (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:3479:7)
    at mergeDefaults (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:6242:9)
    at baseMergeDeep (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:3526:11)
    at /Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:3486:11
    at arrayEach (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:522:11)
    at baseMerge (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:3479:7)
    at /Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:13119:7
    at /Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:4686:13
    at apply (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:481:27)
    at /Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:3829:16
    at apply (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:484:17)
    at Function.<anonymous> (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:12494:14)
    at apply (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:480:27)
    at Function.defaultsDeep (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/lodash/lodash.js:3829:16)
    at deepextend (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/seneca/lib/common.js:187:25)
    at Seneca.web (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/web.js:31:101)
    at define_plugin (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/seneca/lib/plugins.js:313:26)
    at Seneca.plugin_definition (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/seneca/lib/plugins.js:88:16)
    at Array.done (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/seneca/seneca.js:950:22)
    at validate_action_message (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/seneca/seneca.js:1398:19)
    at execute_action (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/seneca/seneca.js:880:7)
    at Object.execspec.fn [as orig_fn] (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/seneca/seneca.js:1084:11)
    at Object.timeout_fn [as fn] (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/seneca/node_modules/gate-executor/gate-executor.js:194:12)
    at next (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/seneca/node_modules/gate-executor/gate-executor.js:126:14)
    at process (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/seneca/node_modules/gate-executor/gate-executor.js:175:12)
    at Immediate._onImmediate (/Users/dgonzalez/Documents/NearForm/seneca/seneca-web/node_modules/seneca/node_modules/gate-executor/gate-executor.js:258:7)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by dgonzalez** [comment]
It also happens with hapi (not only express)

**Comment by geek** [comment]
@dgonzalez it looks like an error in the `request.js` module you are using: `Cannot read property 'encrypted' of undefined` and not an issue in lab: https://github.com/hapijs/lab/search?utf8=%E2%9C%93&q=encrypted
