### ISSUE TITLE
Before failure causes all tests to report success underneath

### ISSUE THREAD

**Issue by Myztiq** [hapijs/lab#682]
The following test file causes the tests to be reported as successful. Also, -i is not respected in the report.

Run the following like so: `lab -i 1 --verbose`

```javascript
'use strict'

var Lab = require('lab')
var lab = exports.lab = Lab.script()
var describe = lab.describe
var it = lab.it
var before = lab.before
var beforeEach = lab.beforeEach
var after = lab.after
var afterEach = lab.afterEach

describe('Failure', function () {
  before((done) => {
    done(new Error('Before Fails'))
  })
  describe('Nested', () => {
    it('should report failure', (done) => {
      done()
    })
    it('should not report this test if ran with -i 1', (done) => {
      done()
    })
  })
})
```

It gives the following report:

```
➜  api git:(rework-bdd) ✗ ./node_modules/.bin/lab -i 1 fail.js --verbose
Failure
  Nested
    ✔ 1) should report failure (0 ms)
    ✔ 2) should not report this test if ran with -i 1 (0 ms)


Test script errors:

Before Fails
      at null._onTimeout (/Users/myztiq/runnable/api/fail.js:15:12)
      at Timer.listOnTimeout (timers.js:92:15)

There were 1 test script error(s).

2 tests complete
Test duration: 107 ms
No global variable leaks detected
```

**Comment by hueniverse** [comment]
Closing due to inactivity.
