### ISSUE TITLE
Uncaught exceptions thrown from promise chains don't fail tests 

### ISSUE THREAD

**Issue by Wenzil** [hapijs/lab#708]
I stumbled on a problem with how lab treats errors thrown **in the context of a promise chain**, but that aren't promise rejections due to being thrown **from a separate function stack** because of asynchronicity. 

It's easier to explain with an example. Here's a failing test:

```js
const Lab = require('lab')
const lab = exports.lab = Lab.script()

lab.test('uncaught exception from promise test', (done) => {
  Promise.resolve()
    .then(() => {
      setImmediate(() => {
        throw new Error('test error')
      })
    })
    .catch((err) => {
      // Code never reached (as expected, since the thrown error above is not a promise rejection)
      console.log('handled promise rejection!', err)
      done(err)
    })
})

lab.test('second test', (done) => {
  // Code never reached... Unless we add an 'uncaughtException' handler at the process level,
  // in which case the first case will eventually timeout, which is still undesirable
  console.log('second test started')
  done()
})
```
The error is simply not handled by lab and the process crashes in the first test.

If we add an 'uncaughtException' handler at the process level, the crash is prevented and the first test will eventually timeout, and then the second test will be executed. However, having to wait for the timeout is not desirable. 

Lab should handle uncaught exceptions regardless of where they are thrown from.

**Comment by geek** [comment]
Looks like an issue with domains.


```javascript
const Domain = require('domain');

const d = Domain.create();
d.on('error', (err) => console.log(err));

d.run(() => { Promise.resolve().then(() => { setImmediate(() => { throw new Error('test error'); }) }) .catch((err) => { console.log('handled promise rejection!', err) }); });
```

```
Error: test error
    at Immediate.setImmediate (repl:1:73)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

vs 

```javascript
const Domain = require('domain');

const d = Domain.create();
d.on('error', (err) => console.log(err));

d.run(() => { setImmediate(() => { throw new Error('test error'); }); });
```

```
{ Error: test error
    at Immediate.setImmediate (repl:1:42)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  domain:
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
```

**Comment by cjihrig** [comment]
My understanding is that promises + domains were broken until https://github.com/nodejs/node/pull/12489. Care to give it a shot with latest Node master?

**Comment by geek** [comment]
@cjihrig works!

```
v8.0.0-pre
~/github/node (master) $ ./node
> const Domain = require('domain');
undefined
> const d = Domain.create();
undefined
> d.on('error', (err) => console.log(err));
Domain {
  domain: null,
  _events: { error: [Function] },
  _eventsCount: 1,
  _maxListeners: undefined,
  members: [] }
> d.run(() => { Promise.resolve().then(() => { setImmediate(() => { throw new Error('test error'); }) }) .catch((err) => { console.log('handled promise rejection!', err) }); });
undefined
> { Error: test error
    at Immediate.setImmediate [as _onImmediate] (repl:1:73)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
  domain:
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
```
