### ISSUE TITLE
"Invalid or unexpected token" error when running lab.cmd in .bin on Win10

### ISSUE THREAD

**Issue by jcollum-cambia** [hapijs/lab#725]
Assumed I had something configured incorrectly, so I tried uuid: 

```
c:\projects\constraint-listener>.\node_modules\.bin\uuid.cmd
b154d794-18f1-4374-8f4b-982e05b2bf1e
```
But when running lab, I get this: 
```
c:\projects\constraint-listener>.\node_modules\.bin\lab.cmd
c:\projects\constraint-listener\test\index.js:1
(function (exports, require, module, __filename, __dirname) { ��
                                                              ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at testFiles.forEach (c:\projects\constraint-listener\node_modules\lab\lib\cli.js:121:21)
    at Array.forEach (native)
    at Object.internals.traverse (c:\projects\constraint-listener\node_modules\lab\lib\cli.js:117:15)
    at Object.exports.run (c:\projects\constraint-listener\node_modules\lab\lib\cli.js:62:31)
    at Object.<anonymous> (c:\projects\constraint-listener\node_modules\lab\bin\lab:50:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

```

Versions: 

```
$ node --version
v6.11.0

$ cat .\node_modules\lab\package.json | grep version.\:
  "version": "14.1.0"

```
Windows 10. Sorry, I know doing node dev in Windows sucks but that's what I got 👎

**Comment by cjihrig** [comment]
If you run `node c:\projects\constraint-listener\test\index.js`, do you get the same error?

**Comment by jcollum-cambia** [comment]
Yes. 

OK turns out that Lab was trying to run an empty file. Deleted the file and it ran fine. Don't know if that is a bug or just a config error. Pretty cryptic error though.

**Comment by cjihrig** [comment]
That error wasn't coming from lab, but node itself. There were some characters in that file (probably hidden) that it didn't recognize.

**Comment by jcollum-cambia** [comment]
I tried deleting all the characters and still go the error. Oh well. I'll leave the issue and close it since google didn't find much when I searched.
