### ISSUE TITLE
Implement jsdom in Lab test

### ISSUE THREAD

**Issue by dancespiele** [hapijs/lab#775]
Hello I would like to know how can implement jsdom in Lab or some way to work with global window, because although I import the jsdom-global library I get the error `window is not defined`

This is my code test: 
```
import { Route } from 'pyrite-server/lib/src/route';
import { plugins } from 'typegoose/lib/data';
import { connect } from 'tls';
import * as Lab from 'lab';
import * as Code from 'code';
import * as request from 'request-promise';
import {PyriteConnect} from 'pyrite-connect';
import {EmitterPlugin} from 'pyrite-connect-emitter';
import {addPerson, delPerson} from './requests';

require('jsdom-global')();

const lab = Lab.script();

export { lab };

lab.experiment('People', () => {
  let id: string;
  let connect: PyriteConnect;
  let routes;

  lab.before(async () => {
    connect = new PyriteConnect({
      url: 'http://localhost:8000',
      plugins: [new EmitterPlugin]
    });

    routes = await connect.getRoutes();
  })
  lab.test('add person have to be success', async () => {
    const res = await routes.People.on.addPeople(addPerson);
    id = res.body._id;
    Code.expect(res.statusCode).to.be.equal(200);
    Code.expect(res.body.name).to.be.equal("camion");
    routes.People.off.addPeople();
  });
  lab.test('delete person have to be success', async () => {
    delPerson.uri = `${delPerson.uri}/${id}`;
    const res = await request(delPerson);
    Code.expect(res.statusCode).to.be.equal(200);
    Code.expect(res.body.ok).to.be.equal(1);
  });
});
```
and I get this error:
```
ReferenceError: window is not defined
    at /home/razorpack/develop/listing-people-api/node_modules/mithril/mithril.js:374:25
    at Object.<anonymous> (/home/razorpack/develop/listing-people-api/node_modules/mithril/mithril.js:1243:2)
    at Module._compile (module.js:624:30)
    at Object.require.extensions.(anonymous function) [as .js] (/home/razorpack/develop/listing-people-api/node_modules/lab/lib/transform.js:20:28)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/razorpack/develop/listing-people-api/node_modules/pyrite-connect/lib/utils.js:3:11)
    at Module._compile (module.js:624:30)
    at Object.require.extensions.(anonymous function) [as .js] (/home/razorpack/develop/listing-people-api/node_modules/lab/lib/transform.js:20:28)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/razorpack/develop/listing-people-api/node_modules/pyrite-connect/lib/connect.js:3:17)
    at Module._compile (module.js:624:30)
    at Object.require.extensions.(anonymous function) [as .js] (/home/razorpack/develop/listing-people-api/node_modules/lab/lib/transform.js:20:28)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/razorpack/develop/listing-people-api/node_modules/pyrite-connect/lib/index.js:3:17)
    at Module._compile (module.js:624:30)
    at Object.require.extensions.(anonymous function) [as .js] (/home/razorpack/develop/listing-people-api/node_modules/lab/lib/transform.js:20:28)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/razorpack/develop/listing-people-api/test/test/people.ts:7:1)
    at Module._compile (module.js:624:30)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/razorpack/develop/listing-people-api/node_modules/lab/lib/transform.js:20:28)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at testFiles.forEach (/home/razorpack/develop/listing-people-api/node_modules/lab/lib/cli.js:136:13)
    at Array.forEach (<anonymous>)
    at Object.internals.traverse (/home/razorpack/develop/listing-people-api/node_modules/lab/lib/cli.js:130:15)
    at Object.exports.run (/home/razorpack/develop/listing-people-api/node_modules/lab/lib/cli.js:64:31)
    at main (/home/razorpack/develop/listing-people-api/node_modules/lab/bin/lab:52:50)
    at Object.<anonymous> (/home/razorpack/develop/listing-people-api/node_modules/lab/bin/lab:56:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
npm ERR! Test failed.  See above for more details.
```
The error come from pyrite-connect which depends of mithril

Also there aren't any plugins to Karma and even if I try to assert the jsdom-global I get the same error

**Comment by geek** [comment]
@dancespiele try running `require('jsdom-global')();` before your imports
