### ISSUE TITLE
Anyone having issues running tests on GitLab? 

### ISSUE THREAD

**Issue by jcollum** [hapijs/lab#787]
The situation usually goes like this: 

1. write a bunch of tests
1. run tests: 
     31 tests complete
     Test duration: 564 ms 
     Assertions count: 105 (verbosity: 3.39)
     No global variable leaks detected
     Coverage: 91.94% (47/583)
1. Ok good, push code. 
1. Gitlab CI: run tests inside a docker container (because our CI server doesn't have node6 👎  )
1. Result: 
    16 of 31 tests failed
    Test duration: 9857 ms
    Assertions count: 55 (verbosity: 1.77)
    No global variable leaks detected
    Coverage: 76.37% (121/512)
1. Reason: 

```
Multiple callbacks received in test "Before Enrichment .enrich" (done)
      at runCallback (timers.js:676:20)
      at tryOnImmediate (timers.js:645:5)
      at processImmediate [as _immediateCallback] (timers.js:617:5)

Timed out (2000ms) - Before Enrichment .enrich
      at ontimeout (timers.js:386:11)
      at tryOnTimeout (timers.js:250:5)
      at Timer.listOnTimeout (timers.js:214:5)
```

This kind of thing happens all the time but **only on the build box**. Does this happen to anyone else?  My integration tests (docker-compose) run into the same problem. 

Tests run fine locally. Tests run fine inside the docker container locally. 

Anyone got suggestions for dealing with this sort of vague "runs fine locally, but not on build box" sort of failures? 

Need more info? Is this just a problem with Gitlab that I have to deal with?

**Comment by Marsup** [comment]
If gitlab is slow just increase the timeout.

**Comment by jcollum** [comment]
What about the `Multiple callbacks received in test "Before Enrichment .enrich" (done)`?

**Comment by Marsup** [comment]
2 sides of the same problem. Test timeouts are there to fail tests that are actually stuck, if it ends up finishing you get multiple callbacks. What are you doing in that before?

**Comment by jcollum** [comment]
> if it ends up finishing you get multiple callbacks.

Ah, ok, that makes sense now, thanks. 

>What are you doing in that before? 

Tearing down and recreating several minio-s3 buckets and elasticmq queues. Maybe our build box is just too anemic.

**Comment by geek** [comment]
@jcollum what version of lab are you running.

**Comment by jcollum** [comment]
14.3.1

If the fix is to go to 15, I really can't, this is a project that is wrapping up and I can't introduce breaking changes now.

**Comment by geek** [comment]
Thanks. I was hoping that I'd fixed the error message to be clearer in that version regarding the timeout. I'll log this as a bug for v14/15, to investigate/fix the error message in the case of a timeout to be clear.

**Comment by hueniverse** [comment]
Closing due to inactivity.
