### ISSUE TITLE
Error: Cannot find module 'babel-eslint'

### ISSUE THREAD

**Issue by damusix** [hapijs/lab#795]
Using: 
- `"hapi": "^11.1.2"`
- `"code": "^2.1.1"`
- `"lab": "^10.3.0"`

Whenever I run`lab -L -v`, all tests pass, then the process hangs and never exits. 
The only thing I get is this:

```
/Users/damusix/myapp/node_modules/lab/node_modules/eslint/lib/util/module-resolver.js:75
            throw new Error("Cannot find module '" + name + "'");
            ^

Error: Cannot find module 'babel-eslint'
    at Object.ModuleResolver.resolve (/Users/damusix/myapp/node_modules/lab/node_modules/eslint/lib/util/module-resolver.js:75:19)
    at Object.load (/Users/damusix/myapp/node_modules/lab/node_modules/eslint/lib/config/config-file.js:518:42)
    at loadConfig (/Users/damusix/myapp/node_modules/lab/node_modules/eslint/lib/config.js:64:33)
    at getLocalConfig (/Users/damusix/myapp/node_modules/lab/node_modules/eslint/lib/config.js:136:23)
    at Config.getConfig (/Users/damusix/myapp/node_modules/lab/node_modules/eslint/lib/config.js:263:22)
    at processText (/Users/damusix/myapp/node_modules/lab/node_modules/eslint/lib/cli-engine.js:222:27)
    at processFile (/Users/damusix/myapp/node_modules/lab/node_modules/eslint/lib/cli-engine.js:297:18)
    at executeOnFile (/Users/damusix/myapp/node_modules/lab/node_modules/eslint/lib/cli-engine.js:669:23)
    at /Users/damusix/myapp/node_modules/lab/node_modules/eslint/lib/cli-engine.js:706:13
    at Array.forEach (native)
```

and lint never runs

This is strangely happening with only 1 hapi app. I have over 100 tests, but linter stopped working recently I have no idea why. I've googled and haven't found any issues relating to this.

This is what I've tried so far:
- remove `node_modules` and `package-lock.json` and `npm i`
- app is in node 4, so I tried in other versions of node (5,6,7,8)
- confirm `babel-eslint` is installed
- confirm `babel-eslint` is installed inside `node_modules/lab/node_modules` (node 4 specific)
- re-install node 4
- remove all node versions in `nvm`, and manually remove any trace of, and re-install node 4
- asset path is using nvm node 4

Other developers have confirmed this doesn't happened on their machines. Doesn't happen on docker machines.

Any ideas why this is happening on my particular env? Could it be a one-off? Further suggestions?

Please advise! It's driving me nuts!

**Comment by geek** [comment]
@damusix please try updating to a more recent version of lab (v14.x or v15)

**Comment by damusix** [comment]
@geek Same thing :/ I'm thinking it might be environment because it works on ever other machine.

**Comment by geek** [comment]
@damusix I bet you are right, I haven't seen this before. Also, we don't include babel-eslint... you may want to check to see if you have a parent .eslintrc file.
