### ISSUE TITLE
Multiple callbacks or thrown errors received in test 

### ISSUE THREAD

**Issue by rkdaredevil** [hapijs/lab#800]
I'm using lab version 13.0.3 and 13.0.1

here's my code snippet 
it('should generate a payload with source and target parameters defined when event has payload as attribute', (done) => {

    const event = {
      'payload': {
        'uuid': '123',
        'pcOnly': false,
        'callback': '',
        'airliftStatus': 0
      },
      'dummy': '111'
    };

    const context = {};
    return Lambda.handler(event, context, (err, res) => {

      if (err) {
        return done(err);

      }
      expect(res.type).to.equal('airlift');
      expect(res.payload.source).to.be.a.string().and.contain(['reprojected', '123', 'processing-jobs']);
      expect(res.payload.target).to.be.a.string().and.contain(['deliverables', '123', 'dummy_name']);
      expect(res.project.atStatus).to.be.equal(1);
      done();

    });

  });

Error Logs
Test script errors:

Multiple callbacks or thrown errors received in test "index should generate a payload with source and target parameters defined" (done)
      at runCallback (timers.js:793:20)
      at tryOnImmediate (timers.js:751:5)
      at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by Marsup** [comment]
This looks correct and there's nothing we can run from this code, so sorry but you'll have to look for your mistake on your own.
