### ISSUE TITLE
Global lodash without include in every file which is imported to test

### ISSUE THREAD

**Issue by dancespiele** [hapijs/lab#900]
Hello,

Are there any possibilities to use globally lodash without having to import lodash in every file which I want test?

I get this error if I import a file without lodash Imported:

```
_ is not defined
ReferenceError: _ is not defined
    at Object.<anonymous> (/Users/francisco/projects/sg-sdk/src/platform/facebookInstant/modules/social/xPromo.js:23:26)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/francisco/projects/sg-sdk/node_modules/lab/lib/transform.js:21:28)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/francisco/projects/sg-sdk/test/xPromo.test.js:17:58)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/francisco/projects/sg-sdk/node_modules/lab/lib/transform.js:21:28)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at testFiles.forEach (/Users/francisco/projects/sg-sdk/node_modules/lab/lib/cli.js:137:13)
    at Array.forEach (<anonymous>)
    at Object.internals.traverse (/Users/francisco/projects/sg-sdk/node_modules/lab/lib/cli.js:131:15)
    at Object.exports.run (/Users/francisco/projects/sg-sdk/node_modules/lab/lib/cli.js:64:31)
    at main (/Users/francisco/projects/sg-sdk/node_modules/lab/bin/lab:57:48)
    at Object.<anonymous> (/Users/francisco/projects/sg-sdk/node_modules/lab/bin/lab:61:1)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:826:3)
npm ERR! Test failed.  See above for more details.
```

To fix this error I have to import lodash in every file something that makes useless the webpack task which include lodash globally.

**Comment by dancespiele** [comment]
Maybe I can import from the file already built by webpack but are there anything to include lodash globally in lab instead of build the application with webpack?

**Comment by Nargonath** [comment]
I'm not aware of such feature, sorry but I doubt it though.

Regarding to webpack, it doesn't do magic. IMO it should build your code to add the import in it so if you run with `lab` the code that has not gone through your webpack pipeline then I cannot see how it would work.
