### ISSUE TITLE
Failed to exec test when tests succeed

### ISSUE THREAD

**Issue by kjenney** [hapijs/lab#903]
I'm running my tests in CircleCI on the node:8.10 image. All of my tests succeed but an error code is returned:

```
86 tests complete (1 skipped)
Test duration: 885 ms
The following leaks were detected:SharedArrayBuffer, Atomics, WebAssembly

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-service@0.9.0 test: `lab test -p -v`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-service@0.9.0 test script.
```

Here is the output of the debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'test' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle my-service@0.9.0~pretest: my-service@0.9.0
6 info lifecycle my-service@0.9.0~test: my-service@0.9.0
7 verbose lifecycle my-service@0.9.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle my-service@0.9.0~test: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/project/
node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle my-service@0.9.0~test: CWD: /root/project
10 silly lifecycle my-service@0.9.0~test: Args: [ '-c', 'lab test -p -v' ]
11 silly lifecycle my-service@0.9.0~test: Returned: code: 1  signal: null
12 info lifecycle my-service@0.9.0~test: Failed to exec test script
13 verbose stack Error: my-service@0.9.0 test: `lab test -p -v`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid my-service@0.9.0...
```

**Comment by geek** [comment]
This is likely due to running an older version of lab. What version of lab are you running?

**Comment by kjenney** [comment]
I was running 10.3.0. I upgraded to 14.2.2 and now the tests pass with exit code 0. Thanks!

**Comment by geek** [comment]
@kjenney great! Thanks for the follow-up
